// Auto-generated from Basic English 850 word list (Wiktionary).
// Fields: w=word, ipa=phonetic, zh=Chinese, pos=part of speech, ex=example, cat=category
const WORD_CAT_LABELS = {"operations": "功能词 Operations", "general": "通用名词 General", "thing": "实物名词 Things", "adjective": "形容词 Qualities"};

const WORDS = [
  {"w": "come", "ipa": "/kʌm/", "zh": "来", "pos": "v.", "ex": "I come to school every day.", "cat": "operations"},
  {"w": "get", "ipa": "/ɡet/", "zh": "得到", "pos": "v.", "ex": "She will get a book.", "cat": "operations"},
  {"w": "give", "ipa": "/ɡɪv/", "zh": "给", "pos": "v.", "ex": "Please give me the pen.", "cat": "operations"},
  {"w": "go", "ipa": "/ɡoʊ/", "zh": "去", "pos": "v.", "ex": "We go to the park.", "cat": "operations"},
  {"w": "keep", "ipa": "/kiːp/", "zh": "保持", "pos": "v.", "ex": "He will keep the money.", "cat": "operations"},
  {"w": "let", "ipa": "/let/", "zh": "让", "pos": "v.", "ex": "Let him go home.", "cat": "operations"},
  {"w": "make", "ipa": "/meɪk/", "zh": "制作", "pos": "v.", "ex": "I make a cake.", "cat": "operations"},
  {"w": "put", "ipa": "/pʊt/", "zh": "放", "pos": "v.", "ex": "Put the book on the table.", "cat": "operations"},
  {"w": "seem", "ipa": "/siːm/", "zh": "似乎", "pos": "v.", "ex": "He seems happy today.", "cat": "operations"},
  {"w": "take", "ipa": "/teɪk/", "zh": "拿", "pos": "v.", "ex": "Take the apple please.", "cat": "operations"},
  {"w": "be", "ipa": "/biː/", "zh": "是", "pos": "v.", "ex": "I want to be free.", "cat": "operations"},
  {"w": "do", "ipa": "/duː/", "zh": "做", "pos": "v.", "ex": "They do the work.", "cat": "operations"},
  {"w": "have", "ipa": "/hæv/", "zh": "有", "pos": "v.", "ex": "I have a dog.", "cat": "operations"},
  {"w": "say", "ipa": "/seɪ/", "zh": "说", "pos": "v.", "ex": "She says hello to me.", "cat": "operations"},
  {"w": "see", "ipa": "/siː/", "zh": "看见", "pos": "v.", "ex": "I see a bird.", "cat": "operations"},
  {"w": "send", "ipa": "/send/", "zh": "发送", "pos": "v.", "ex": "He will send a letter.", "cat": "operations"},
  {"w": "may", "ipa": "/meɪ/", "zh": "可以", "pos": "aux.", "ex": "You may leave now.", "cat": "operations"},
  {"w": "will", "ipa": "/wɪl/", "zh": "将", "pos": "aux.", "ex": "I will go home.", "cat": "operations"},
  {"w": "about", "ipa": "/əˈbaʊt/", "zh": "关于", "pos": "prep.", "ex": "He talks about the book.", "cat": "operations"},
  {"w": "across", "ipa": "/əˈkrɒs/", "zh": "穿过", "pos": "prep.", "ex": "Walk across the street.", "cat": "operations"},
  {"w": "after", "ipa": "/ˈɑːftər/", "zh": "在…后", "pos": "prep.", "ex": "We play after school.", "cat": "operations"},
  {"w": "against", "ipa": "/əˈɡenst/", "zh": "反对", "pos": "prep.", "ex": "He is against the plan.", "cat": "operations"},
  {"w": "among", "ipa": "/əˈmʌŋ/", "zh": "在…中", "pos": "prep.", "ex": "She sits among the kids.", "cat": "operations"},
  {"w": "at", "ipa": "/æt/", "zh": "在", "pos": "prep.", "ex": "He is at the door.", "cat": "operations"},
  {"w": "before", "ipa": "/bɪˈfɔːr/", "zh": "在…前", "pos": "prep.", "ex": "Wash before eating.", "cat": "operations"},
  {"w": "between", "ipa": "/bɪˈtwiːn/", "zh": "在…间", "pos": "prep.", "ex": "The ball is between us.", "cat": "operations"},
  {"w": "by", "ipa": "/baɪ/", "zh": "由", "pos": "prep.", "ex": "The book is by him.", "cat": "operations"},
  {"w": "down", "ipa": "/daʊn/", "zh": "向下", "pos": "prep.", "ex": "The cup fell down.", "cat": "operations"},
  {"w": "from", "ipa": "/frɒm/", "zh": "从", "pos": "prep.", "ex": "I come from China.", "cat": "operations"},
  {"w": "in", "ipa": "/ɪn/", "zh": "在…里", "pos": "prep.", "ex": "The cat is in the box.", "cat": "operations"},
  {"w": "off", "ipa": "/ɒf/", "zh": "离开", "pos": "prep.", "ex": "Take off your hat.", "cat": "operations"},
  {"w": "on", "ipa": "/ɒn/", "zh": "在…上", "pos": "prep.", "ex": "The book is on the desk.", "cat": "operations"},
  {"w": "over", "ipa": "/ˈoʊvər/", "zh": "在…上方", "pos": "prep.", "ex": "The bird flies over the tree.", "cat": "operations"},
  {"w": "through", "ipa": "/θruː/", "zh": "穿过", "pos": "prep.", "ex": "We walk through the gate.", "cat": "operations"},
  {"w": "to", "ipa": "/tuː/", "zh": "到", "pos": "prep.", "ex": "I go to the shop.", "cat": "operations"},
  {"w": "under", "ipa": "/ˈʌndər/", "zh": "在…下", "pos": "prep.", "ex": "The shoe is under the bed.", "cat": "operations"},
  {"w": "up", "ipa": "/ʌp/", "zh": "向上", "pos": "prep.", "ex": "He went up the hill.", "cat": "operations"},
  {"w": "with", "ipa": "/wɪð/", "zh": "和", "pos": "prep.", "ex": "I play with you.", "cat": "operations"},
  {"w": "as", "ipa": "/æz/", "zh": "作为", "pos": "prep.", "ex": "He works as a teacher.", "cat": "operations"},
  {"w": "for", "ipa": "/fɔːr/", "zh": "为了", "pos": "prep.", "ex": "This is for you.", "cat": "operations"},
  {"w": "of", "ipa": "/ɒv/", "zh": "的", "pos": "prep.", "ex": "The colour of the sky.", "cat": "operations"},
  {"w": "till", "ipa": "/tɪl/", "zh": "直到", "pos": "prep.", "ex": "Wait till the rain stops.", "cat": "operations"},
  {"w": "than", "ipa": "/ðæn/", "zh": "比", "pos": "prep.", "ex": "He is taller than me.", "cat": "operations"},
  {"w": "a", "ipa": "/eɪ/", "zh": "一个", "pos": "det.", "ex": "I see a cat.", "cat": "operations"},
  {"w": "the", "ipa": "/ðə/", "zh": "这/那", "pos": "det.", "ex": "The dog is big.", "cat": "operations"},
  {"w": "all", "ipa": "/ɔːl/", "zh": "全部", "pos": "det.", "ex": "All the boys laugh.", "cat": "operations"},
  {"w": "any", "ipa": "/ˈeni/", "zh": "任何", "pos": "det.", "ex": "Do you have any money?", "cat": "operations"},
  {"w": "every", "ipa": "/ˈevri/", "zh": "每个", "pos": "det.", "ex": "Every child likes play.", "cat": "operations"},
  {"w": "no", "ipa": "/noʊ/", "zh": "没有", "pos": "det.", "ex": "She has no book.", "cat": "operations"},
  {"w": "other", "ipa": "/ˈʌðər/", "zh": "其他的", "pos": "det.", "ex": "The other boy left.", "cat": "operations"},
  {"w": "some", "ipa": "/sʌm/", "zh": "一些", "pos": "det.", "ex": "I eat some bread.", "cat": "operations"},
  {"w": "such", "ipa": "/sʌtʃ/", "zh": "这样的", "pos": "det.", "ex": "Such a dog is small.", "cat": "operations"},
  {"w": "that", "ipa": "/ðæt/", "zh": "那个", "pos": "det.", "ex": "That car is red.", "cat": "operations"},
  {"w": "this", "ipa": "/ðɪs/", "zh": "这个", "pos": "det.", "ex": "This apple is sweet.", "cat": "operations"},
  {"w": "I", "ipa": "/aɪ/", "zh": "我", "pos": "pron.", "ex": "I like the sun.", "cat": "operations"},
  {"w": "he", "ipa": "/hiː/", "zh": "他", "pos": "pron.", "ex": "He reads a book.", "cat": "operations"},
  {"w": "you", "ipa": "/juː/", "zh": "你", "pos": "pron.", "ex": "You are my friend.", "cat": "operations"},
  {"w": "who", "ipa": "/huː/", "zh": "谁", "pos": "pron.", "ex": "Who is that man?", "cat": "operations"},
  {"w": "and", "ipa": "/ænd/", "zh": "和", "pos": "conj.", "ex": "He and she laugh.", "cat": "operations"},
  {"w": "because", "ipa": "/bɪˈkɒz/", "zh": "因为", "pos": "conj.", "ex": "I cry because I am sad.", "cat": "operations"},
  {"w": "but", "ipa": "/bʌt/", "zh": "但是", "pos": "conj.", "ex": "He is small but strong.", "cat": "operations"},
  {"w": "or", "ipa": "/ɔːr/", "zh": "或者", "pos": "conj.", "ex": "Tea or coffee?", "cat": "operations"},
  {"w": "if", "ipa": "/ɪf/", "zh": "如果", "pos": "conj.", "ex": "If it rains we stay.", "cat": "operations"},
  {"w": "though", "ipa": "/ðoʊ/", "zh": "虽然", "pos": "conj.", "ex": "He went out though tired.", "cat": "operations"},
  {"w": "while", "ipa": "/waɪl/", "zh": "当…时", "pos": "conj.", "ex": "She sings while we dance.", "cat": "operations"},
  {"w": "how", "ipa": "/haʊ/", "zh": "如何", "pos": "adv.", "ex": "How are you today?", "cat": "operations"},
  {"w": "when", "ipa": "/wen/", "zh": "何时", "pos": "adv.", "ex": "When does he come?", "cat": "operations"},
  {"w": "where", "ipa": "/wer/", "zh": "哪里", "pos": "adv.", "ex": "Where is the book?", "cat": "operations"},
  {"w": "why", "ipa": "/waɪ/", "zh": "为什么", "pos": "adv.", "ex": "Why do you laugh?", "cat": "operations"},
  {"w": "again", "ipa": "/əˈɡen/", "zh": "再次", "pos": "adv.", "ex": "He called again.", "cat": "operations"},
  {"w": "ever", "ipa": "/ˈevər/", "zh": "曾经", "pos": "adv.", "ex": "Have you ever won?", "cat": "operations"},
  {"w": "far", "ipa": "/fɑːr/", "zh": "远", "pos": "adv.", "ex": "The school is far.", "cat": "operations"},
  {"w": "forward", "ipa": "/ˈfɔːrwərd/", "zh": "向前", "pos": "adv.", "ex": "Move forward slowly.", "cat": "operations"},
  {"w": "here", "ipa": "/hɪr/", "zh": "这里", "pos": "adv.", "ex": "Come here please.", "cat": "operations"},
  {"w": "near", "ipa": "/nɪr/", "zh": "近", "pos": "adv.", "ex": "The shop is near.", "cat": "operations"},
  {"w": "now", "ipa": "/naʊ/", "zh": "现在", "pos": "adv.", "ex": "He is here now.", "cat": "operations"},
  {"w": "out", "ipa": "/aʊt/", "zh": "外面", "pos": "adv.", "ex": "The dog went out.", "cat": "operations"},
  {"w": "still", "ipa": "/stɪl/", "zh": "仍然", "pos": "adv.", "ex": "She is still sleeping.", "cat": "operations"},
  {"w": "then", "ipa": "/ðen/", "zh": "然后", "pos": "adv.", "ex": "We ate and then left.", "cat": "operations"},
  {"w": "there", "ipa": "/ðer/", "zh": "那里", "pos": "adv.", "ex": "The book is there.", "cat": "operations"},
  {"w": "together", "ipa": "/təˈɡeðər/", "zh": "一起", "pos": "adv.", "ex": "We play together.", "cat": "operations"},
  {"w": "well", "ipa": "/wel/", "zh": "好", "pos": "adv.", "ex": "He sings very well.", "cat": "operations"},
  {"w": "almost", "ipa": "/ˈɔːlmoʊst/", "zh": "几乎", "pos": "adv.", "ex": "I almost fell down.", "cat": "operations"},
  {"w": "enough", "ipa": "/ɪˈnʌf/", "zh": "足够", "pos": "adv.", "ex": "I have eaten enough.", "cat": "operations"},
  {"w": "even", "ipa": "/ˈiːvn/", "zh": "甚至", "pos": "adv.", "ex": "He even laughed.", "cat": "operations"},
  {"w": "little", "ipa": "/ˈlɪtl/", "zh": "少", "pos": "adv.", "ex": "She smiled a little.", "cat": "operations"},
  {"w": "much", "ipa": "/mʌtʃ/", "zh": "很多", "pos": "adv.", "ex": "Thank you very much.", "cat": "operations"},
  {"w": "not", "ipa": "/nɒt/", "zh": "不", "pos": "adv.", "ex": "He is not here.", "cat": "operations"},
  {"w": "only", "ipa": "/ˈoʊnli/", "zh": "仅仅", "pos": "adv.", "ex": "I only have one.", "cat": "operations"},
  {"w": "quite", "ipa": "/kwaɪt/", "zh": "相当", "pos": "adv.", "ex": "The film is quite good.", "cat": "operations"},
  {"w": "so", "ipa": "/soʊ/", "zh": "所以", "pos": "adv.", "ex": "I am tired so rest.", "cat": "operations"},
  {"w": "very", "ipa": "/ˈveri/", "zh": "非常", "pos": "adv.", "ex": "She is very kind.", "cat": "operations"},
  {"w": "tomorrow", "ipa": "/təˈmɒroʊ/", "zh": "明天", "pos": "adv.", "ex": "We leave tomorrow.", "cat": "operations"},
  {"w": "yesterday", "ipa": "/ˈjestərdeɪ/", "zh": "昨天", "pos": "adv.", "ex": "He came yesterday.", "cat": "operations"},
  {"w": "north", "ipa": "/nɔːrθ/", "zh": "北", "pos": "n.", "ex": "The wind is from north.", "cat": "operations"},
  {"w": "south", "ipa": "/saʊθ/", "zh": "南", "pos": "n.", "ex": "The south is warm.", "cat": "operations"},
  {"w": "east", "ipa": "/iːst/", "zh": "东", "pos": "n.", "ex": "The sun rises in east.", "cat": "operations"},
  {"w": "west", "ipa": "/west/", "zh": "西", "pos": "n.", "ex": "The west is dry.", "cat": "operations"},
  {"w": "please", "ipa": "/pliːz/", "zh": "请", "pos": "adv.", "ex": "Please open the door.", "cat": "operations"},
  {"w": "yes", "ipa": "/jes/", "zh": "是", "pos": "adv.", "ex": "Yes I will go.", "cat": "operations"},
  {"w": "account", "ipa": "/əˈkaʊnt/", "zh": "账户", "pos": "n.", "ex": "I opened a bank account today.", "cat": "general"},
  {"w": "act", "ipa": "/ækt/", "zh": "行为", "pos": "n.", "ex": "The act was kind and helpful.", "cat": "general"},
  {"w": "addition", "ipa": "/əˈdɪʃən/", "zh": "加法", "pos": "n.", "ex": "The addition was quick and easy.", "cat": "general"},
  {"w": "adjustment", "ipa": "/əˈdʒʌstmənt/", "zh": "调整", "pos": "n.", "ex": "He made an adjustment to the seat.", "cat": "general"},
  {"w": "advertisement", "ipa": "/ədˈvɜːrtəsmənt/", "zh": "广告", "pos": "n.", "ex": "The advertisement was on television.", "cat": "general"},
  {"w": "agreement", "ipa": "/əˈɡriːmənt/", "zh": "协议", "pos": "n.", "ex": "We signed the agreement this morning.", "cat": "general"},
  {"w": "air", "ipa": "/ɛər/", "zh": "空气", "pos": "n.", "ex": "The air is fresh and clean.", "cat": "general"},
  {"w": "amount", "ipa": "/əˈmaʊnt/", "zh": "数量", "pos": "n.", "ex": "The amount of water was small.", "cat": "general"},
  {"w": "amusement", "ipa": "/əˈmjuːzmənt/", "zh": "娱乐", "pos": "n.", "ex": "The game was a fun amusement.", "cat": "general"},
  {"w": "animal", "ipa": "/ˈænɪməl/", "zh": "动物", "pos": "n.", "ex": "The animal is very small.", "cat": "general"},
  {"w": "answer", "ipa": "/ˈænsər/", "zh": "回答", "pos": "n.", "ex": "Her answer was short and clear.", "cat": "general"},
  {"w": "apparatus", "ipa": "/ˌæpəˈreɪtəs/", "zh": "装置", "pos": "n.", "ex": "The apparatus is in the lab.", "cat": "general"},
  {"w": "approval", "ipa": "/əˈpruːvəl/", "zh": "批准", "pos": "n.", "ex": "He gave his approval to us.", "cat": "general"},
  {"w": "argument", "ipa": "/ˈɑːrɡjumənt/", "zh": "争论", "pos": "n.", "ex": "Their argument was very loud.", "cat": "general"},
  {"w": "art", "ipa": "/ɑːrt/", "zh": "艺术", "pos": "n.", "ex": "She likes the art on wall.", "cat": "general"},
  {"w": "attack", "ipa": "/əˈtæk/", "zh": "攻击", "pos": "n.", "ex": "The attack was sudden and quick.", "cat": "general"},
  {"w": "attempt", "ipa": "/əˈtempt/", "zh": "尝试", "pos": "n.", "ex": "His attempt was a failure.", "cat": "general"},
  {"w": "attention", "ipa": "/əˈtenʃən/", "zh": "注意", "pos": "n.", "ex": "She paid attention to the dog.", "cat": "general"},
  {"w": "attraction", "ipa": "/əˈtrækʃən/", "zh": "吸引", "pos": "n.", "ex": "The park is a big attraction.", "cat": "general"},
  {"w": "authority", "ipa": "/əˈθɔːrəti/", "zh": "权威", "pos": "n.", "ex": "The authority made a new rule.", "cat": "general"},
  {"w": "back", "ipa": "/bæk/", "zh": "背部", "pos": "n.", "ex": "He hurt his back yesterday.", "cat": "general"},
  {"w": "balance", "ipa": "/ˈbæləns/", "zh": "平衡", "pos": "n.", "ex": "The balance was not easy.", "cat": "general"},
  {"w": "base", "ipa": "/beɪs/", "zh": "基础", "pos": "n.", "ex": "The base of the tree is wide.", "cat": "general"},
  {"w": "behaviour", "ipa": "/bɪˈheɪvjər/", "zh": "行为", "pos": "n.", "ex": "His behaviour was not good.", "cat": "general"},
  {"w": "belief", "ipa": "/bɪˈliːf/", "zh": "信念", "pos": "n.", "ex": "My belief is very strong.", "cat": "general"},
  {"w": "birth", "ipa": "/bɜːrθ/", "zh": "出生", "pos": "n.", "ex": "The birth was early this year.", "cat": "general"},
  {"w": "bit", "ipa": "/bɪt/", "zh": "一点", "pos": "n.", "ex": "He ate a bit of cake.", "cat": "general"},
  {"w": "bite", "ipa": "/baɪt/", "zh": "咬", "pos": "n.", "ex": "The dog gave a small bite.", "cat": "general"},
  {"w": "blood", "ipa": "/blʌd/", "zh": "血", "pos": "n.", "ex": "The blood was on the floor.", "cat": "general"},
  {"w": "blow", "ipa": "/bloʊ/", "zh": "打击", "pos": "n.", "ex": "He gave a hard blow.", "cat": "general"},
  {"w": "body", "ipa": "/ˈbɒdi/", "zh": "身体", "pos": "n.", "ex": "Her body is very healthy.", "cat": "general"},
  {"w": "brass", "ipa": "/bræs/", "zh": "黄铜", "pos": "n.", "ex": "The brass is very shiny.", "cat": "general"},
  {"w": "bread", "ipa": "/brɛd/", "zh": "面包", "pos": "n.", "ex": "I ate the bread for lunch.", "cat": "general"},
  {"w": "breath", "ipa": "/brɛθ/", "zh": "呼吸", "pos": "n.", "ex": "Take a deep breath now.", "cat": "general"},
  {"w": "brother", "ipa": "/ˈbrʌðər/", "zh": "兄弟", "pos": "n.", "ex": "My brother is a tall boy.", "cat": "general"},
  {"w": "building", "ipa": "/ˈbɪldɪŋ/", "zh": "建筑物", "pos": "n.", "ex": "The building is very old.", "cat": "general"},
  {"w": "burn", "ipa": "/bɜːrn/", "zh": "烧伤", "pos": "n.", "ex": "He has a bad burn.", "cat": "general"},
  {"w": "burst", "ipa": "/bɜːrst/", "zh": "爆裂", "pos": "n.", "ex": "The burst was very loud.", "cat": "general"},
  {"w": "business", "ipa": "/ˈbɪznəs/", "zh": "商业", "pos": "n.", "ex": "His business is doing well.", "cat": "general"},
  {"w": "butter", "ipa": "/ˈbʌtər/", "zh": "黄油", "pos": "n.", "ex": "The butter is on bread.", "cat": "general"},
  {"w": "canvas", "ipa": "/ˈkænvəs/", "zh": "帆布", "pos": "n.", "ex": "The canvas is very strong.", "cat": "general"},
  {"w": "care", "ipa": "/kɛər/", "zh": "关心", "pos": "n.", "ex": "She gave the baby care.", "cat": "general"},
  {"w": "cause", "ipa": "/kɔːz/", "zh": "原因", "pos": "n.", "ex": "The cause was not clear.", "cat": "general"},
  {"w": "chalk", "ipa": "/tʃɔːk/", "zh": "粉笔", "pos": "n.", "ex": "The chalk is on the desk.", "cat": "general"},
  {"w": "chance", "ipa": "/tʃɑːns/", "zh": "机会", "pos": "n.", "ex": "He got a good chance.", "cat": "general"},
  {"w": "change", "ipa": "/tʃeɪndʒ/", "zh": "变化", "pos": "n.", "ex": "The change was very big.", "cat": "general"},
  {"w": "cloth", "ipa": "/klɒθ/", "zh": "布", "pos": "n.", "ex": "The cloth is very clean.", "cat": "general"},
  {"w": "coal", "ipa": "/koʊl/", "zh": "煤", "pos": "n.", "ex": "The coal is black and dirty.", "cat": "general"},
  {"w": "colour", "ipa": "/ˈkʌlər/", "zh": "颜色", "pos": "n.", "ex": "The colour is bright red.", "cat": "general"},
  {"w": "comfort", "ipa": "/ˈkʌmfərt/", "zh": "舒适", "pos": "n.", "ex": "The bed is a comfort.", "cat": "general"},
  {"w": "committee", "ipa": "/kəˈmɪti/", "zh": "委员会", "pos": "n.", "ex": "The committee met today.", "cat": "general"},
  {"w": "company", "ipa": "/ˈkʌmpəni/", "zh": "公司", "pos": "n.", "ex": "The company is very large.", "cat": "general"},
  {"w": "comparison", "ipa": "/kəmˈpærɪsən/", "zh": "比较", "pos": "n.", "ex": "The comparison was quite fair.", "cat": "general"},
  {"w": "competition", "ipa": "/ˌkɒmpəˈtɪʃən/", "zh": "竞争", "pos": "n.", "ex": "He won the competition easily.", "cat": "general"},
  {"w": "condition", "ipa": "/kənˈdɪʃən/", "zh": "条件", "pos": "n.", "ex": "The condition is not good.", "cat": "general"},
  {"w": "connection", "ipa": "/kəˈnekʃən/", "zh": "连接", "pos": "n.", "ex": "The connection is very weak.", "cat": "general"},
  {"w": "control", "ipa": "/kənˈtroʊl/", "zh": "控制", "pos": "n.", "ex": "He has control of the dog.", "cat": "general"},
  {"w": "cook", "ipa": "/kʊk/", "zh": "厨师", "pos": "n.", "ex": "The cook made some bread.", "cat": "general"},
  {"w": "copper", "ipa": "/ˈkɒpər/", "zh": "铜", "pos": "n.", "ex": "The copper is a metal.", "cat": "general"},
  {"w": "copy", "ipa": "/ˈkɒpi/", "zh": "副本", "pos": "n.", "ex": "I made a copy of it.", "cat": "general"},
  {"w": "cork", "ipa": "/kɔːrk/", "zh": "软木", "pos": "n.", "ex": "The cork is from a tree.", "cat": "general"},
  {"w": "cotton", "ipa": "/ˈkɒtn/", "zh": "棉花", "pos": "n.", "ex": "The shirt is made of cotton.", "cat": "general"},
  {"w": "cough", "ipa": "/kɒf/", "zh": "咳嗽", "pos": "n.", "ex": "He has a bad cough.", "cat": "general"},
  {"w": "country", "ipa": "/ˈkʌntri/", "zh": "国家", "pos": "n.", "ex": "The country is very large.", "cat": "general"},
  {"w": "cover", "ipa": "/ˈkʌvər/", "zh": "盖子", "pos": "n.", "ex": "The cover is on the pot.", "cat": "general"},
  {"w": "crack", "ipa": "/kræk/", "zh": "裂缝", "pos": "n.", "ex": "The crack is on the wall.", "cat": "general"},
  {"w": "credit", "ipa": "/ˈkrɛdɪt/", "zh": "信用", "pos": "n.", "ex": "He has good credit.", "cat": "general"},
  {"w": "crime", "ipa": "/kraɪm/", "zh": "犯罪", "pos": "n.", "ex": "The crime was very sad.", "cat": "general"},
  {"w": "crush", "ipa": "/krʌʃ/", "zh": "压碎", "pos": "n.", "ex": "The crush was very loud.", "cat": "general"},
  {"w": "cry", "ipa": "/kraɪ/", "zh": "哭", "pos": "n.", "ex": "The baby gave a loud cry.", "cat": "general"},
  {"w": "current", "ipa": "/ˈkʌrənt/", "zh": "电流", "pos": "n.", "ex": "The current is very strong.", "cat": "general"},
  {"w": "curve", "ipa": "/kɜːrv/", "zh": "曲线", "pos": "n.", "ex": "The road has a sharp curve.", "cat": "general"},
  {"w": "damage", "ipa": "/ˈdæmɪdʒ/", "zh": "损害", "pos": "n.", "ex": "The storm caused damage.", "cat": "general"},
  {"w": "danger", "ipa": "/ˈdeɪndʒər/", "zh": "危险", "pos": "n.", "ex": "The dog is a danger.", "cat": "general"},
  {"w": "daughter", "ipa": "/ˈdɔːtər/", "zh": "女儿", "pos": "n.", "ex": "His daughter is a girl.", "cat": "general"},
  {"w": "day", "ipa": "/deɪ/", "zh": "天", "pos": "n.", "ex": "The day is very sunny.", "cat": "general"},
  {"w": "death", "ipa": "/dɛθ/", "zh": "死亡", "pos": "n.", "ex": "The death was very sad.", "cat": "general"},
  {"w": "debt", "ipa": "/dɛt/", "zh": "债务", "pos": "n.", "ex": "He paid the debt today.", "cat": "general"},
  {"w": "decision", "ipa": "/dɪˈsɪʒən/", "zh": "决定", "pos": "n.", "ex": "Her decision was a good one.", "cat": "general"},
  {"w": "degree", "ipa": "/dɪˈɡriː/", "zh": "度数", "pos": "n.", "ex": "The angle is thirty degree.", "cat": "general"},
  {"w": "design", "ipa": "/dɪˈzaɪn/", "zh": "设计", "pos": "n.", "ex": "The design is very simple.", "cat": "general"},
  {"w": "desire", "ipa": "/dɪˈzaɪər/", "zh": "愿望", "pos": "n.", "ex": "He has a strong desire.", "cat": "general"},
  {"w": "destruction", "ipa": "/dɪˈstrʌkʃən/", "zh": "破坏", "pos": "n.", "ex": "The war caused destruction.", "cat": "general"},
  {"w": "detail", "ipa": "/dɪˈteɪl/", "zh": "细节", "pos": "n.", "ex": "The detail was very small.", "cat": "general"},
  {"w": "development", "ipa": "/dɪˈvɛləpmənt/", "zh": "发展", "pos": "n.", "ex": "The development was very fast.", "cat": "general"},
  {"w": "digestion", "ipa": "/daɪˈdʒestʃən/", "zh": "消化", "pos": "n.", "ex": "The digestion was quite slow.", "cat": "general"},
  {"w": "direction", "ipa": "/dɪˈrɛkʃən/", "zh": "方向", "pos": "n.", "ex": "He gave the right direction.", "cat": "general"},
  {"w": "discovery", "ipa": "/dɪsˈkʌvəri/", "zh": "发现", "pos": "n.", "ex": "The discovery was a surprise.", "cat": "general"},
  {"w": "discussion", "ipa": "/dɪsˈkʌʃən/", "zh": "讨论", "pos": "n.", "ex": "The discussion was very long.", "cat": "general"},
  {"w": "disease", "ipa": "/dɪˈziːz/", "zh": "疾病", "pos": "n.", "ex": "The disease is very serious.", "cat": "general"},
  {"w": "disgust", "ipa": "/dɪsˈɡʌst/", "zh": "厌恶", "pos": "n.", "ex": "He felt a deep disgust.", "cat": "general"},
  {"w": "distance", "ipa": "/ˈdɪstəns/", "zh": "距离", "pos": "n.", "ex": "The distance is quite far.", "cat": "general"},
  {"w": "distribution", "ipa": "/ˌdɪstrɪˈbjuːʃən/", "zh": "分布", "pos": "n.", "ex": "The distribution was not fair.", "cat": "general"},
  {"w": "division", "ipa": "/dɪˈvɪʒən/", "zh": "分开", "pos": "n.", "ex": "The division is not equal.", "cat": "general"},
  {"w": "doubt", "ipa": "/daʊt/", "zh": "怀疑", "pos": "n.", "ex": "He had a small doubt.", "cat": "general"},
  {"w": "drink", "ipa": "/drɪŋk/", "zh": "饮料", "pos": "n.", "ex": "The drink is very cold.", "cat": "general"},
  {"w": "driving", "ipa": "/ˈdraɪvɪŋ/", "zh": "驾驶", "pos": "n.", "ex": "Driving is a useful skill.", "cat": "general"},
  {"w": "dust", "ipa": "/dʌst/", "zh": "灰尘", "pos": "n.", "ex": "The dust is on the table.", "cat": "general"},
  {"w": "earth", "ipa": "/ɜːrθ/", "zh": "地球", "pos": "n.", "ex": "The earth is very large.", "cat": "general"},
  {"w": "edge", "ipa": "/ɛdʒ/", "zh": "边缘", "pos": "n.", "ex": "The edge is very sharp.", "cat": "general"},
  {"w": "education", "ipa": "/ˌɛdʒuˈkeɪʃən/", "zh": "教育", "pos": "n.", "ex": "Education is very important.", "cat": "general"},
  {"w": "effect", "ipa": "/ɪˈfɛkt/", "zh": "效果", "pos": "n.", "ex": "The effect was very clear.", "cat": "general"},
  {"w": "end", "ipa": "/ɛnd/", "zh": "结束", "pos": "n.", "ex": "The end was a surprise.", "cat": "general"},
  {"w": "error", "ipa": "/ˈɛrər/", "zh": "错误", "pos": "n.", "ex": "The error was very small.", "cat": "general"},
  {"w": "event", "ipa": "/ɪˈvɛnt/", "zh": "事件", "pos": "n.", "ex": "The event was a big one.", "cat": "general"},
  {"w": "example", "ipa": "/ɪɡˈzæmpəl/", "zh": "例子", "pos": "n.", "ex": "This is a good example.", "cat": "general"},
  {"w": "exchange", "ipa": "/ɪksˈtʃeɪndʒ/", "zh": "交换", "pos": "n.", "ex": "The exchange was very fair.", "cat": "general"},
  {"w": "existence", "ipa": "/ɪɡˈzɪstəns/", "zh": "存在", "pos": "n.", "ex": "The existence was a mystery.", "cat": "general"},
  {"w": "expansion", "ipa": "/ɪkˈspænʃən/", "zh": "扩张", "pos": "n.", "ex": "The expansion was very fast.", "cat": "general"},
  {"w": "experience", "ipa": "/ɪkˈspɪəriəns/", "zh": "经验", "pos": "n.", "ex": "He has much experience.", "cat": "general"},
  {"w": "expert", "ipa": "/ˈɛkspɜːrt/", "zh": "专家", "pos": "n.", "ex": "The expert is very busy.", "cat": "general"},
  {"w": "fact", "ipa": "/fækt/", "zh": "事实", "pos": "n.", "ex": "The fact is very clear.", "cat": "general"},
  {"w": "fall", "ipa": "/fɔːl/", "zh": "秋天", "pos": "n.", "ex": "The fall is very cool.", "cat": "general"},
  {"w": "family", "ipa": "/ˈfæməli/", "zh": "家庭", "pos": "n.", "ex": "My family is very large.", "cat": "general"},
  {"w": "father", "ipa": "/ˈfɑːðər/", "zh": "父亲", "pos": "n.", "ex": "My father is a tall man.", "cat": "general"},
  {"w": "fear", "ipa": "/fɪər/", "zh": "恐惧", "pos": "n.", "ex": "The dog felt a deep fear.", "cat": "general"},
  {"w": "feeling", "ipa": "/ˈfiːlɪŋ/", "zh": "感觉", "pos": "n.", "ex": "She had a strange feeling.", "cat": "general"},
  {"w": "fiction", "ipa": "/ˈfɪkʃən/", "zh": "小说", "pos": "n.", "ex": "The fiction was very good.", "cat": "general"},
  {"w": "field", "ipa": "/fiːld/", "zh": "田野", "pos": "n.", "ex": "The field is very green.", "cat": "general"},
  {"w": "fight", "ipa": "/faɪt/", "zh": "战斗", "pos": "n.", "ex": "The fight was very short.", "cat": "general"},
  {"w": "fire", "ipa": "/faɪər/", "zh": "火", "pos": "n.", "ex": "The fire is very hot.", "cat": "general"},
  {"w": "flame", "ipa": "/fleɪm/", "zh": "火焰", "pos": "n.", "ex": "The flame is very bright.", "cat": "general"},
  {"w": "flight", "ipa": "/flaɪt/", "zh": "飞行", "pos": "n.", "ex": "The flight was very smooth.", "cat": "general"},
  {"w": "flower", "ipa": "/ˈflaʊər/", "zh": "花", "pos": "n.", "ex": "The flower is very red.", "cat": "general"},
  {"w": "fold", "ipa": "/foʊld/", "zh": "折叠", "pos": "n.", "ex": "He made a neat fold.", "cat": "general"},
  {"w": "food", "ipa": "/fuːd/", "zh": "食物", "pos": "n.", "ex": "The food is very good.", "cat": "general"},
  {"w": "force", "ipa": "/fɔːrs/", "zh": "力量", "pos": "n.", "ex": "The force was very strong.", "cat": "general"},
  {"w": "form", "ipa": "/fɔːrm/", "zh": "形式", "pos": "n.", "ex": "The form is very simple.", "cat": "general"},
  {"w": "friend", "ipa": "/frɛnd/", "zh": "朋友", "pos": "n.", "ex": "He is a good friend.", "cat": "general"},
  {"w": "front", "ipa": "/frʌnt/", "zh": "前面", "pos": "n.", "ex": "The front is very clean.", "cat": "general"},
  {"w": "fruit", "ipa": "/fruːt/", "zh": "水果", "pos": "n.", "ex": "The fruit is very sweet.", "cat": "general"},
  {"w": "glass", "ipa": "/ɡlæs/", "zh": "玻璃；玻璃杯", "pos": "n.", "ex": "She drank water from a glass.", "cat": "general"},
  {"w": "gold", "ipa": "/ɡoʊld/", "zh": "黄金", "pos": "n.", "ex": "The ring is made of gold.", "cat": "general"},
  {"w": "government", "ipa": "/ˈɡʌvərnmənt/", "zh": "政府", "pos": "n.", "ex": "The government made a new law.", "cat": "general"},
  {"w": "grain", "ipa": "/ɡreɪn/", "zh": "谷物", "pos": "n.", "ex": "He ate a piece of grain.", "cat": "general"},
  {"w": "grass", "ipa": "/ɡræs/", "zh": "草", "pos": "n.", "ex": "The cow eats green grass.", "cat": "general"},
  {"w": "grip", "ipa": "/ɡrɪp/", "zh": "抓握", "pos": "n.", "ex": "He has a strong grip.", "cat": "general"},
  {"w": "group", "ipa": "/ɡruːp/", "zh": "组；群", "pos": "n.", "ex": "A group of girls laughed.", "cat": "general"},
  {"w": "growth", "ipa": "/ɡroʊθ/", "zh": "生长", "pos": "n.", "ex": "The plant shows fast growth.", "cat": "general"},
  {"w": "guide", "ipa": "/ɡaɪd/", "zh": "向导", "pos": "n.", "ex": "The guide led the tour.", "cat": "general"},
  {"w": "harbour", "ipa": "/ˈhɑːrbər/", "zh": "港口", "pos": "n.", "ex": "The ship entered the harbour.", "cat": "general"},
  {"w": "harmony", "ipa": "/ˈhɑːrməni/", "zh": "和谐", "pos": "n.", "ex": "They lived in harmony.", "cat": "general"},
  {"w": "hate", "ipa": "/heɪt/", "zh": "仇恨", "pos": "n.", "ex": "His hate was obvious.", "cat": "general"},
  {"w": "hearing", "ipa": "/ˈhɪrɪŋ/", "zh": "听觉", "pos": "n.", "ex": "Her hearing is very good.", "cat": "general"},
  {"w": "heat", "ipa": "/hiːt/", "zh": "热", "pos": "n.", "ex": "The heat was too much.", "cat": "general"},
  {"w": "help", "ipa": "/help/", "zh": "帮助", "pos": "n.", "ex": "He gave me help.", "cat": "general"},
  {"w": "history", "ipa": "/ˈhɪstəri/", "zh": "历史", "pos": "n.", "ex": "I read a history book.", "cat": "general"},
  {"w": "hole", "ipa": "/hoʊl/", "zh": "洞", "pos": "n.", "ex": "The dog dug a hole.", "cat": "general"},
  {"w": "hope", "ipa": "/hoʊp/", "zh": "希望", "pos": "n.", "ex": "She had a small hope.", "cat": "general"},
  {"w": "hour", "ipa": "/ˈaʊər/", "zh": "小时", "pos": "n.", "ex": "Wait for one hour.", "cat": "general"},
  {"w": "humour", "ipa": "/ˈhjuːmər/", "zh": "幽默", "pos": "n.", "ex": "His humour made us laugh.", "cat": "general"},
  {"w": "ice", "ipa": "/aɪs/", "zh": "冰", "pos": "n.", "ex": "The ice is cold.", "cat": "general"},
  {"w": "idea", "ipa": "/aɪˈdiːə/", "zh": "想法", "pos": "n.", "ex": "I have a good idea.", "cat": "general"},
  {"w": "impulse", "ipa": "/ˈɪmpʌls/", "zh": "冲动", "pos": "n.", "ex": "He acted on impulse.", "cat": "general"},
  {"w": "increase", "ipa": "/ɪnˈkriːs/", "zh": "增加", "pos": "n.", "ex": "There was an increase.", "cat": "general"},
  {"w": "industry", "ipa": "/ˈɪndəstri/", "zh": "工业", "pos": "n.", "ex": "The industry grew fast.", "cat": "general"},
  {"w": "ink", "ipa": "/ɪŋk/", "zh": "墨水", "pos": "n.", "ex": "The pen needs ink.", "cat": "general"},
  {"w": "insect", "ipa": "/ˈɪnsekt/", "zh": "昆虫", "pos": "n.", "ex": "The insect flew away.", "cat": "general"},
  {"w": "instrument", "ipa": "/ˈɪnstrəmənt/", "zh": "仪器", "pos": "n.", "ex": "He played an instrument.", "cat": "general"},
  {"w": "insurance", "ipa": "/ɪnˈʃʊrəns/", "zh": "保险", "pos": "n.", "ex": "He bought car insurance.", "cat": "general"},
  {"w": "interest", "ipa": "/ˈɪntrəst/", "zh": "兴趣", "pos": "n.", "ex": "She showed interest.", "cat": "general"},
  {"w": "invention", "ipa": "/ɪnˈvenʃn/", "zh": "发明", "pos": "n.", "ex": "The invention helped many.", "cat": "general"},
  {"w": "iron", "ipa": "/ˈaɪərn/", "zh": "铁", "pos": "n.", "ex": "The iron is heavy.", "cat": "general"},
  {"w": "jelly", "ipa": "/ˈdʒeli/", "zh": "果冻", "pos": "n.", "ex": "The child ate jelly.", "cat": "general"},
  {"w": "join", "ipa": "/dʒɔɪn/", "zh": "连接；加入", "pos": "n.", "ex": "The join was hidden.", "cat": "general"},
  {"w": "journey", "ipa": "/ˈdʒɜːrni/", "zh": "旅程", "pos": "n.", "ex": "The journey was long.", "cat": "general"},
  {"w": "judge", "ipa": "/dʒʌdʒ/", "zh": "法官", "pos": "n.", "ex": "The judge spoke loudly.", "cat": "general"},
  {"w": "jump", "ipa": "/dʒʌmp/", "zh": "跳", "pos": "n.", "ex": "He made a big jump.", "cat": "general"},
  {"w": "kick", "ipa": "/kɪk/", "zh": "踢", "pos": "n.", "ex": "The kick was hard.", "cat": "general"},
  {"w": "kiss", "ipa": "/kɪs/", "zh": "吻", "pos": "n.", "ex": "She gave a kiss.", "cat": "general"},
  {"w": "knowledge", "ipa": "/ˈnɒlɪdʒ/", "zh": "知识", "pos": "n.", "ex": "Knowledge is power.", "cat": "general"},
  {"w": "land", "ipa": "/lænd/", "zh": "土地", "pos": "n.", "ex": "The land is fertile.", "cat": "general"},
  {"w": "language", "ipa": "/ˈlæŋɡwɪdʒ/", "zh": "语言", "pos": "n.", "ex": "English is a language.", "cat": "general"},
  {"w": "laugh", "ipa": "/læf/", "zh": "笑", "pos": "n.", "ex": "He gave a loud laugh.", "cat": "general"},
  {"w": "law", "ipa": "/lɔː/", "zh": "法律", "pos": "n.", "ex": "The law is fair.", "cat": "general"},
  {"w": "lead", "ipa": "/led/", "zh": "铅", "pos": "n.", "ex": "The pipe is made of lead.", "cat": "general"},
  {"w": "learning", "ipa": "/ˈlɜːrnɪŋ/", "zh": "学习", "pos": "n.", "ex": "Learning takes time.", "cat": "general"},
  {"w": "leather", "ipa": "/ˈleðər/", "zh": "皮革", "pos": "n.", "ex": "The bag is leather.", "cat": "general"},
  {"w": "letter", "ipa": "/ˈletər/", "zh": "信；字母", "pos": "n.", "ex": "I wrote a letter.", "cat": "general"},
  {"w": "level", "ipa": "/ˈlevl/", "zh": "水平", "pos": "n.", "ex": "The water level rose.", "cat": "general"},
  {"w": "lift", "ipa": "/lɪft/", "zh": "电梯", "pos": "n.", "ex": "Take the lift up.", "cat": "general"},
  {"w": "light", "ipa": "/laɪt/", "zh": "光", "pos": "n.", "ex": "The light is bright.", "cat": "general"},
  {"w": "limit", "ipa": "/ˈlɪmɪt/", "zh": "限制", "pos": "n.", "ex": "There is a limit.", "cat": "general"},
  {"w": "linen", "ipa": "/ˈlɪnɪn/", "zh": "亚麻布", "pos": "n.", "ex": "The shirt is linen.", "cat": "general"},
  {"w": "liquid", "ipa": "/ˈlɪkwɪd/", "zh": "液体", "pos": "n.", "ex": "Water is a liquid.", "cat": "general"},
  {"w": "list", "ipa": "/lɪst/", "zh": "清单", "pos": "n.", "ex": "Make a list.", "cat": "general"},
  {"w": "look", "ipa": "/lʊk/", "zh": "看", "pos": "n.", "ex": "He gave a look.", "cat": "general"},
  {"w": "loss", "ipa": "/lɔːs/", "zh": "损失", "pos": "n.", "ex": "The loss was sad.", "cat": "general"},
  {"w": "love", "ipa": "/lʌv/", "zh": "爱", "pos": "n.", "ex": "Love is sweet.", "cat": "general"},
  {"w": "machine", "ipa": "/məˈʃiːn/", "zh": "机器", "pos": "n.", "ex": "The machine is loud.", "cat": "general"},
  {"w": "man", "ipa": "/mæn/", "zh": "男人", "pos": "n.", "ex": "The man smiled.", "cat": "general"},
  {"w": "manager", "ipa": "/ˈmænɪdʒər/", "zh": "经理", "pos": "n.", "ex": "The manager is busy.", "cat": "general"},
  {"w": "mark", "ipa": "/mɑːrk/", "zh": "标记", "pos": "n.", "ex": "He left a mark.", "cat": "general"},
  {"w": "market", "ipa": "/ˈmɑːrkɪt/", "zh": "市场", "pos": "n.", "ex": "She went to market.", "cat": "general"},
  {"w": "mass", "ipa": "/mæs/", "zh": "质量；团", "pos": "n.", "ex": "The mass is large.", "cat": "general"},
  {"w": "meal", "ipa": "/miːl/", "zh": "餐", "pos": "n.", "ex": "We had a meal.", "cat": "general"},
  {"w": "measure", "ipa": "/ˈmeʒər/", "zh": "测量", "pos": "n.", "ex": "Use a measure.", "cat": "general"},
  {"w": "meat", "ipa": "/miːt/", "zh": "肉", "pos": "n.", "ex": "The meat is fresh.", "cat": "general"},
  {"w": "meeting", "ipa": "/ˈmiːtɪŋ/", "zh": "会议", "pos": "n.", "ex": "The meeting is over.", "cat": "general"},
  {"w": "memory", "ipa": "/ˈmeməri/", "zh": "记忆", "pos": "n.", "ex": "I lost my memory.", "cat": "general"},
  {"w": "metal", "ipa": "/ˈmetl/", "zh": "金属", "pos": "n.", "ex": "The metal is cold.", "cat": "general"},
  {"w": "middle", "ipa": "/ˈmɪdl/", "zh": "中间", "pos": "n.", "ex": "He stood in the middle.", "cat": "general"},
  {"w": "milk", "ipa": "/mɪlk/", "zh": "牛奶", "pos": "n.", "ex": "The milk is white.", "cat": "general"},
  {"w": "mind", "ipa": "/maɪnd/", "zh": "心智", "pos": "n.", "ex": "He changed his mind.", "cat": "general"},
  {"w": "mine", "ipa": "/maɪn/", "zh": "矿", "pos": "n.", "ex": "The mine is deep.", "cat": "general"},
  {"w": "minute", "ipa": "/ˈmɪnɪt/", "zh": "分钟", "pos": "n.", "ex": "Wait a minute.", "cat": "general"},
  {"w": "mist", "ipa": "/mɪst/", "zh": "薄雾", "pos": "n.", "ex": "The mist cleared slowly.", "cat": "general"},
  {"w": "money", "ipa": "/ˈmʌni/", "zh": "钱", "pos": "n.", "ex": "He saved money.", "cat": "general"},
  {"w": "month", "ipa": "/mʌnθ/", "zh": "月", "pos": "n.", "ex": "This month is busy.", "cat": "general"},
  {"w": "morning", "ipa": "/ˈmɔːrnɪŋ/", "zh": "早晨", "pos": "n.", "ex": "The morning was calm.", "cat": "general"},
  {"w": "mother", "ipa": "/ˈmʌðər/", "zh": "母亲", "pos": "n.", "ex": "My mother cooks.", "cat": "general"},
  {"w": "motion", "ipa": "/ˈmoʊʃn/", "zh": "运动", "pos": "n.", "ex": "The motion stopped.", "cat": "general"},
  {"w": "mountain", "ipa": "/ˈmaʊntn/", "zh": "山", "pos": "n.", "ex": "The mountain is high.", "cat": "general"},
  {"w": "move", "ipa": "/muːv/", "zh": "移动", "pos": "n.", "ex": "That was a good move.", "cat": "general"},
  {"w": "music", "ipa": "/ˈmjuːzɪk/", "zh": "音乐", "pos": "n.", "ex": "The music is loud.", "cat": "general"},
  {"w": "name", "ipa": "/neɪm/", "zh": "名字", "pos": "n.", "ex": "Her name is May.", "cat": "general"},
  {"w": "nation", "ipa": "/ˈneɪʃn/", "zh": "国家", "pos": "n.", "ex": "The nation is peaceful.", "cat": "general"},
  {"w": "need", "ipa": "/niːd/", "zh": "需要", "pos": "n.", "ex": "He felt a need.", "cat": "general"},
  {"w": "news", "ipa": "/njuːz/", "zh": "新闻", "pos": "n.", "ex": "The news is good.", "cat": "general"},
  {"w": "night", "ipa": "/naɪt/", "zh": "夜晚", "pos": "n.", "ex": "The night is dark.", "cat": "general"},
  {"w": "noise", "ipa": "/nɔɪz/", "zh": "噪音", "pos": "n.", "ex": "The noise woke me.", "cat": "general"},
  {"w": "note", "ipa": "/noʊt/", "zh": "笔记", "pos": "n.", "ex": "He wrote a note.", "cat": "general"},
  {"w": "number", "ipa": "/ˈnʌmbər/", "zh": "数字", "pos": "n.", "ex": "The number is seven.", "cat": "general"},
  {"w": "observation", "ipa": "/ˌɑːbzərˈveɪʃn/", "zh": "观察", "pos": "n.", "ex": "Her observation was sharp.", "cat": "general"},
  {"w": "offer", "ipa": "/ˈɔːfər/", "zh": "提议", "pos": "n.", "ex": "He made an offer.", "cat": "general"},
  {"w": "oil", "ipa": "/ɔɪl/", "zh": "油", "pos": "n.", "ex": "The oil is slippery.", "cat": "general"},
  {"w": "operation", "ipa": "/ˌɑːpəˈreɪʃn/", "zh": "操作", "pos": "n.", "ex": "The operation succeeded.", "cat": "general"},
  {"w": "opinion", "ipa": "/əˈpɪnjən/", "zh": "意见", "pos": "n.", "ex": "His opinion differs.", "cat": "general"},
  {"w": "order", "ipa": "/ˈɔːrdər/", "zh": "命令；顺序", "pos": "n.", "ex": "The order is clear.", "cat": "general"},
  {"w": "organization", "ipa": "/ˌɔːrɡənəˈzeɪʃn/", "zh": "组织", "pos": "n.", "ex": "The organization helped us.", "cat": "general"},
  {"w": "ornament", "ipa": "/ˈɔːrnəmənt/", "zh": "装饰品", "pos": "n.", "ex": "The ornament is pretty.", "cat": "general"},
  {"w": "owner", "ipa": "/ˈoʊnər/", "zh": "所有者", "pos": "n.", "ex": "The owner left.", "cat": "general"},
  {"w": "page", "ipa": "/peɪdʒ/", "zh": "页", "pos": "n.", "ex": "The page is clean and white.", "cat": "general"},
  {"w": "pain", "ipa": "/peɪn/", "zh": "疼痛", "pos": "n.", "ex": "He feels pain in his arm.", "cat": "general"},
  {"w": "paint", "ipa": "/peɪnt/", "zh": "油漆", "pos": "n.", "ex": "The paint is wet and red.", "cat": "general"},
  {"w": "paper", "ipa": "/peɪpər/", "zh": "纸", "pos": "n.", "ex": "She wrote on the paper.", "cat": "general"},
  {"w": "part", "ipa": "/pɑːrt/", "zh": "部分", "pos": "n.", "ex": "This is part of the book.", "cat": "general"},
  {"w": "paste", "ipa": "/peɪst/", "zh": "浆糊", "pos": "n.", "ex": "He used paste for the paper.", "cat": "general"},
  {"w": "payment", "ipa": "/ˈpeɪmənt/", "zh": "付款", "pos": "n.", "ex": "The payment is due today.", "cat": "general"},
  {"w": "peace", "ipa": "/piːs/", "zh": "和平", "pos": "n.", "ex": "We want peace in the world.", "cat": "general"},
  {"w": "person", "ipa": "/ˈpɜːrsn/", "zh": "人", "pos": "n.", "ex": "A person is at the door.", "cat": "general"},
  {"w": "place", "ipa": "/pleɪs/", "zh": "地方", "pos": "n.", "ex": "This is a good place.", "cat": "general"},
  {"w": "plant", "ipa": "/plænt/", "zh": "植物", "pos": "n.", "ex": "The plant is very green.", "cat": "general"},
  {"w": "play", "ipa": "/pleɪ/", "zh": "戏剧", "pos": "n.", "ex": "We saw a play yesterday.", "cat": "general"},
  {"w": "pleasure", "ipa": "/ˈpleʒər/", "zh": "愉快", "pos": "n.", "ex": "He read with pleasure.", "cat": "general"},
  {"w": "point", "ipa": "/pɔɪnt/", "zh": "点", "pos": "n.", "ex": "The point is very sharp.", "cat": "general"},
  {"w": "poison", "ipa": "/ˈpɔɪzn/", "zh": "毒药", "pos": "n.", "ex": "The poison is in the cup.", "cat": "general"},
  {"w": "polish", "ipa": "/ˈpɒlɪʃ/", "zh": "抛光剂", "pos": "n.", "ex": "Use polish on the shoe.", "cat": "general"},
  {"w": "porter", "ipa": "/ˈpɔːrtər/", "zh": "搬运工", "pos": "n.", "ex": "The porter carried the bag.", "cat": "general"},
  {"w": "position", "ipa": "/pəˈzɪʃn/", "zh": "位置", "pos": "n.", "ex": "The book is in position.", "cat": "general"},
  {"w": "powder", "ipa": "/ˈpaʊdər/", "zh": "粉末", "pos": "n.", "ex": "The powder is white.", "cat": "general"},
  {"w": "power", "ipa": "/ˈpaʊər/", "zh": "力量", "pos": "n.", "ex": "He has great power.", "cat": "general"},
  {"w": "price", "ipa": "/praɪs/", "zh": "价格", "pos": "n.", "ex": "The price is too high.", "cat": "general"},
  {"w": "print", "ipa": "/prɪnt/", "zh": "印刷品", "pos": "n.", "ex": "The print is very clear.", "cat": "general"},
  {"w": "process", "ipa": "/ˈprɑːces/", "zh": "过程", "pos": "n.", "ex": "The process is simple.", "cat": "general"},
  {"w": "produce", "ipa": "/ˈprɑːdjuːs/", "zh": "农产品", "pos": "n.", "ex": "The produce is fresh.", "cat": "general"},
  {"w": "profit", "ipa": "/ˈprɒfɪt/", "zh": "利润", "pos": "n.", "ex": "The profit was small.", "cat": "general"},
  {"w": "property", "ipa": "/ˈprɒpərti/", "zh": "财产", "pos": "n.", "ex": "This is his property.", "cat": "general"},
  {"w": "prose", "ipa": "/proʊz/", "zh": "散文", "pos": "n.", "ex": "He wrote in prose.", "cat": "general"},
  {"w": "protest", "ipa": "/ˈproʊtest/", "zh": "抗议", "pos": "n.", "ex": "The protest was peaceful.", "cat": "general"},
  {"w": "pull", "ipa": "/pʊl/", "zh": "拉", "pos": "n.", "ex": "He gave a strong pull.", "cat": "general"},
  {"w": "punishment", "ipa": "/ˈpʌnɪʃmənt/", "zh": "惩罚", "pos": "n.", "ex": "The punishment was fair.", "cat": "general"},
  {"w": "purpose", "ipa": "/ˈpɜːrpəs/", "zh": "目的", "pos": "n.", "ex": "The purpose is clear.", "cat": "general"},
  {"w": "push", "ipa": "/pʊʃ/", "zh": "推", "pos": "n.", "ex": "He gave a hard push.", "cat": "general"},
  {"w": "quality", "ipa": "/ˈkwɒləti/", "zh": "质量", "pos": "n.", "ex": "The quality is good.", "cat": "general"},
  {"w": "question", "ipa": "/ˈkwestʃən/", "zh": "问题", "pos": "n.", "ex": "She asked a question.", "cat": "general"},
  {"w": "rain", "ipa": "/reɪn/", "zh": "雨", "pos": "n.", "ex": "The rain is very heavy.", "cat": "general"},
  {"w": "range", "ipa": "/reɪndʒ/", "zh": "范围", "pos": "n.", "ex": "The range is wide.", "cat": "general"},
  {"w": "rate", "ipa": "/reɪt/", "zh": "比率", "pos": "n.", "ex": "The rate is low.", "cat": "general"},
  {"w": "ray", "ipa": "/reɪ/", "zh": "光线", "pos": "n.", "ex": "A ray of light came.", "cat": "general"},
  {"w": "reaction", "ipa": "/riˈækʃn/", "zh": "反应", "pos": "n.", "ex": "His reaction was quick.", "cat": "general"},
  {"w": "reading", "ipa": "/ˈriːdɪŋ/", "zh": "阅读", "pos": "n.", "ex": "Reading is good for you.", "cat": "general"},
  {"w": "reason", "ipa": "/ˈriːzn/", "zh": "理由", "pos": "n.", "ex": "The reason is unknown.", "cat": "general"},
  {"w": "record", "ipa": "/ˈrekɔːrd/", "zh": "记录", "pos": "n.", "ex": "The record is broken.", "cat": "general"},
  {"w": "regret", "ipa": "/rɪˈɡret/", "zh": "遗憾", "pos": "n.", "ex": "He felt deep regret.", "cat": "general"},
  {"w": "relation", "ipa": "/rɪˈleɪʃn/", "zh": "关系", "pos": "n.", "ex": "Their relation is close.", "cat": "general"},
  {"w": "religion", "ipa": "/rɪˈlɪdʒən/", "zh": "宗教", "pos": "n.", "ex": "He studies religion.", "cat": "general"},
  {"w": "representative", "ipa": "/ˌreprɪˈzentətɪv/", "zh": "代表", "pos": "n.", "ex": "He is a representative.", "cat": "general"},
  {"w": "request", "ipa": "/rɪˈkwest/", "zh": "请求", "pos": "n.", "ex": "She made a request.", "cat": "general"},
  {"w": "respect", "ipa": "/rɪˈspekt/", "zh": "尊敬", "pos": "n.", "ex": "He earned our respect.", "cat": "general"},
  {"w": "rest", "ipa": "/rest/", "zh": "休息", "pos": "n.", "ex": "He needs a rest.", "cat": "general"},
  {"w": "reward", "ipa": "/rɪˈwɔːrd/", "zh": "奖励", "pos": "n.", "ex": "The reward is big.", "cat": "general"},
  {"w": "rhythm", "ipa": "/ˈrɪðəm/", "zh": "节奏", "pos": "n.", "ex": "The rhythm is slow.", "cat": "general"},
  {"w": "rice", "ipa": "/raɪs/", "zh": "米饭", "pos": "n.", "ex": "We eat rice daily.", "cat": "general"},
  {"w": "river", "ipa": "/ˈrɪvər/", "zh": "河流", "pos": "n.", "ex": "The river is deep.", "cat": "general"},
  {"w": "road", "ipa": "/roʊd/", "zh": "道路", "pos": "n.", "ex": "The road is long.", "cat": "general"},
  {"w": "roll", "ipa": "/roʊl/", "zh": "卷", "pos": "n.", "ex": "He ate a roll.", "cat": "general"},
  {"w": "room", "ipa": "/ruːm/", "zh": "房间", "pos": "n.", "ex": "The room is clean.", "cat": "general"},
  {"w": "rub", "ipa": "/rʌb/", "zh": "摩擦", "pos": "n.", "ex": "He gave it a rub.", "cat": "general"},
  {"w": "rule", "ipa": "/ruːl/", "zh": "规则", "pos": "n.", "ex": "The rule is simple.", "cat": "general"},
  {"w": "run", "ipa": "/rʌn/", "zh": "奔跑", "pos": "n.", "ex": "He went for a run.", "cat": "general"},
  {"w": "salt", "ipa": "/sɔːlt/", "zh": "盐", "pos": "n.", "ex": "The salt is white.", "cat": "general"},
  {"w": "sand", "ipa": "/sænd/", "zh": "沙", "pos": "n.", "ex": "The sand is hot.", "cat": "general"},
  {"w": "scale", "ipa": "/skeɪl/", "zh": "刻度", "pos": "n.", "ex": "The scale is broken.", "cat": "general"},
  {"w": "science", "ipa": "/ˈsaɪəns/", "zh": "科学", "pos": "n.", "ex": "He likes science.", "cat": "general"},
  {"w": "sea", "ipa": "/siː/", "zh": "海", "pos": "n.", "ex": "The sea is blue.", "cat": "general"},
  {"w": "seat", "ipa": "/siːt/", "zh": "座位", "pos": "n.", "ex": "The seat is taken.", "cat": "general"},
  {"w": "secretary", "ipa": "/ˈsekrəteri/", "zh": "秘书", "pos": "n.", "ex": "The secretary is busy.", "cat": "general"},
  {"w": "selection", "ipa": "/sɪˈlekʃn/", "zh": "选择", "pos": "n.", "ex": "The selection is wide.", "cat": "general"},
  {"w": "self", "ipa": "/self/", "zh": "自我", "pos": "n.", "ex": "He knows his self.", "cat": "general"},
  {"w": "sense", "ipa": "/sens/", "zh": "感觉", "pos": "n.", "ex": "She has good sense.", "cat": "general"},
  {"w": "servant", "ipa": "/ˈsɜːrvənt/", "zh": "仆人", "pos": "n.", "ex": "The servant is kind.", "cat": "general"},
  {"w": "sex", "ipa": "/seks/", "zh": "性别", "pos": "n.", "ex": "The sex is male.", "cat": "general"},
  {"w": "shade", "ipa": "/ʃeɪd/", "zh": "阴影", "pos": "n.", "ex": "The shade is cool.", "cat": "general"},
  {"w": "shake", "ipa": "/ʃeɪk/", "zh": "摇动", "pos": "n.", "ex": "He gave a shake.", "cat": "general"},
  {"w": "shame", "ipa": "/ʃeɪm/", "zh": "羞耻", "pos": "n.", "ex": "He felt shame.", "cat": "general"},
  {"w": "shock", "ipa": "/ʃɒk/", "zh": "震惊", "pos": "n.", "ex": "The shock was great.", "cat": "general"},
  {"w": "side", "ipa": "/saɪd/", "zh": "边", "pos": "n.", "ex": "The side is rough.", "cat": "general"},
  {"w": "sign", "ipa": "/saɪn/", "zh": "标志", "pos": "n.", "ex": "The sign is red.", "cat": "general"},
  {"w": "silk", "ipa": "/sɪlk/", "zh": "丝绸", "pos": "n.", "ex": "The silk is soft.", "cat": "general"},
  {"w": "silver", "ipa": "/ˈsɪlvər/", "zh": "银", "pos": "n.", "ex": "The silver is shiny.", "cat": "general"},
  {"w": "sister", "ipa": "/ˈsɪstər/", "zh": "姐妹", "pos": "n.", "ex": "My sister is young.", "cat": "general"},
  {"w": "size", "ipa": "/saɪz/", "zh": "尺寸", "pos": "n.", "ex": "The size is small.", "cat": "general"},
  {"w": "sky", "ipa": "/skaɪ/", "zh": "天空", "pos": "n.", "ex": "The sky is clear.", "cat": "general"},
  {"w": "sleep", "ipa": "/sliːp/", "zh": "睡眠", "pos": "n.", "ex": "He needs sleep.", "cat": "general"},
  {"w": "slip", "ipa": "/slɪp/", "zh": "滑倒", "pos": "n.", "ex": "He had a slip.", "cat": "general"},
  {"w": "slope", "ipa": "/sloʊp/", "zh": "斜坡", "pos": "n.", "ex": "The slope is steep.", "cat": "general"},
  {"w": "smash", "ipa": "/smæʃ/", "zh": "粉碎", "pos": "n.", "ex": "The smash was loud.", "cat": "general"},
  {"w": "smell", "ipa": "/smel/", "zh": "气味", "pos": "n.", "ex": "The smell is sweet.", "cat": "general"},
  {"w": "smile", "ipa": "/smaɪl/", "zh": "微笑", "pos": "n.", "ex": "She gave a smile.", "cat": "general"},
  {"w": "smoke", "ipa": "/smoʊk/", "zh": "烟", "pos": "n.", "ex": "The smoke is black.", "cat": "general"},
  {"w": "sneeze", "ipa": "/sniːz/", "zh": "喷嚏", "pos": "n.", "ex": "He gave a sneeze.", "cat": "general"},
  {"w": "snow", "ipa": "/snoʊ/", "zh": "雪", "pos": "n.", "ex": "The snow is white.", "cat": "general"},
  {"w": "soap", "ipa": "/soʊp/", "zh": "肥皂", "pos": "n.", "ex": "The soap is wet.", "cat": "general"},
  {"w": "society", "ipa": "/səˈsaɪəti/", "zh": "社会", "pos": "n.", "ex": "Society is complex.", "cat": "general"},
  {"w": "son", "ipa": "/sʌn/", "zh": "儿子", "pos": "n.", "ex": "Her son is tall.", "cat": "general"},
  {"w": "song", "ipa": "/sɔːŋ/", "zh": "歌曲", "pos": "n.", "ex": "The song is happy.", "cat": "general"},
  {"w": "sort", "ipa": "/sɔːrt/", "zh": "种类", "pos": "n.", "ex": "This is a sort.", "cat": "general"},
  {"w": "sound", "ipa": "/saʊnd/", "zh": "声音", "pos": "n.", "ex": "The sound is loud.", "cat": "general"},
  {"w": "soup", "ipa": "/suːp/", "zh": "汤", "pos": "n.", "ex": "The soup is hot.", "cat": "general"},
  {"w": "space", "ipa": "/speɪs/", "zh": "空间", "pos": "n.", "ex": "The space is empty.", "cat": "general"},
  {"w": "stage", "ipa": "/steɪdʒ/", "zh": "舞台", "pos": "n.", "ex": "The stage is big.", "cat": "general"},
  {"w": "start", "ipa": "/stɑːrt/", "zh": "开始", "pos": "n.", "ex": "The start was quick.", "cat": "general"},
  {"w": "statement", "ipa": "/ˈsteɪtmənt/", "zh": "陈述", "pos": "n.", "ex": "The statement is false.", "cat": "general"},
  {"w": "steam", "ipa": "/stiːm/", "zh": "蒸汽", "pos": "n.", "ex": "The steam is hot.", "cat": "general"},
  {"w": "steel", "ipa": "/stiːl/", "zh": "钢", "pos": "n.", "ex": "The steel is hard.", "cat": "general"},
  {"w": "step", "ipa": "/step/", "zh": "脚步", "pos": "n.", "ex": "He took a step.", "cat": "general"},
  {"w": "stitch", "ipa": "/stɪtʃ/", "zh": "缝针", "pos": "n.", "ex": "The stitch is small.", "cat": "general"},
  {"w": "stone", "ipa": "/stoʊn/", "zh": "石头", "pos": "n.", "ex": "The stone is heavy.", "cat": "general"},
  {"w": "stop", "ipa": "/stɒp/", "zh": "停止", "pos": "n.", "ex": "He made a stop.", "cat": "general"},
  {"w": "story", "ipa": "/ˈstɔːri/", "zh": "故事", "pos": "n.", "ex": "The story is short.", "cat": "general"},
  {"w": "stretch", "ipa": "/stretʃ/", "zh": "伸展", "pos": "n.", "ex": "He did a stretch.", "cat": "general"},
  {"w": "structure", "ipa": "/ˈstrʌktʃər/", "zh": "结构", "pos": "n.", "ex": "The structure is old.", "cat": "general"},
  {"w": "substance", "ipa": "/ˈsʌbstəns/", "zh": "物质", "pos": "n.", "ex": "The substance is liquid.", "cat": "general"},
  {"w": "sugar", "ipa": "/ˈʃʊɡər/", "zh": "糖", "pos": "n.", "ex": "The sugar is sweet.", "cat": "general"},
  {"w": "suggestion", "ipa": "/səˈdʒestʃən/", "zh": "建议", "pos": "n.", "ex": "He made a suggestion.", "cat": "general"},
  {"w": "summer", "ipa": "/ˈsʌmər/", "zh": "夏天", "pos": "n.", "ex": "Summer is very hot.", "cat": "general"},
  {"w": "support", "ipa": "/səˈpɔːrt/", "zh": "支持", "pos": "n.", "ex": "He gave support.", "cat": "general"},
  {"w": "surprise", "ipa": "/sərˈpraɪz/", "zh": "惊讶", "pos": "n.", "ex": "The surprise was great.", "cat": "general"},
  {"w": "swim", "ipa": "/swɪm/", "zh": "游泳", "pos": "n.", "ex": "He went for a swim.", "cat": "general"},
  {"w": "system", "ipa": "/ˈsɪstəm/", "zh": "系统", "pos": "n.", "ex": "The system is new.", "cat": "general"},
  {"w": "talk", "ipa": "/tɔːk/", "zh": "谈话", "pos": "n.", "ex": "The talk was long.", "cat": "general"},
  {"w": "taste", "ipa": "/teɪst/", "zh": "味道", "pos": "n.", "ex": "The taste is bitter.", "cat": "general"},
  {"w": "tax", "ipa": "/tæks/", "zh": "税", "pos": "n.", "ex": "The tax is high.", "cat": "general"},
  {"w": "teaching", "ipa": "/ˈtiːtʃɪŋ/", "zh": "教学", "pos": "n.", "ex": "Teaching is her job.", "cat": "general"},
  {"w": "tendency", "ipa": "/ˈtendənsi/", "zh": "倾向", "pos": "n.", "ex": "He has that tendency.", "cat": "general"},
  {"w": "test", "ipa": "/test/", "zh": "测试", "pos": "n.", "ex": "The test is easy.", "cat": "general"},
  {"w": "theory", "ipa": "/ˈθɪəri/", "zh": "理论", "pos": "n.", "ex": "The theory is simple.", "cat": "general"},
  {"w": "thing", "ipa": "/θɪŋ/", "zh": "东西", "pos": "n.", "ex": "The thing is broken.", "cat": "general"},
  {"w": "thought", "ipa": "/θɔːt/", "zh": "想法", "pos": "n.", "ex": "His thought is clear.", "cat": "general"},
  {"w": "thunder", "ipa": "/ˈθʌndər/", "zh": "雷", "pos": "n.", "ex": "The thunder is loud.", "cat": "general"},
  {"w": "time", "ipa": "/taɪm/", "zh": "时间", "pos": "n.", "ex": "The time is noon.", "cat": "general"},
  {"w": "tin", "ipa": "/tɪn/", "zh": "锡", "pos": "n.", "ex": "The tin is empty.", "cat": "general"},
  {"w": "top", "ipa": "/tɒp/", "zh": "顶部", "pos": "n.", "ex": "The top is red.", "cat": "general"},
  {"w": "touch", "ipa": "/tʌtʃ/", "zh": "触摸", "pos": "n.", "ex": "He gave a touch.", "cat": "general"},
  {"w": "trade", "ipa": "/treɪd/", "zh": "贸易", "pos": "n.", "ex": "Trade is important.", "cat": "general"},
  {"w": "transport", "ipa": "/ˈtrænspɔːrt/", "zh": "运输", "pos": "n.", "ex": "Transport is slow.", "cat": "general"},
  {"w": "trick", "ipa": "/trɪk/", "zh": "诡计", "pos": "n.", "ex": "The trick is old.", "cat": "general"},
  {"w": "trouble", "ipa": "/ˈtrʌbl/", "zh": "麻烦", "pos": "n.", "ex": "He is in trouble.", "cat": "general"},
  {"w": "turn", "ipa": "/tɜːrn/", "zh": "转弯", "pos": "n.", "ex": "The turn is sharp.", "cat": "general"},
  {"w": "twist", "ipa": "/twɪst/", "zh": "扭曲", "pos": "n.", "ex": "He gave a twist.", "cat": "general"},
  {"w": "unit", "ipa": "/ˈjuːnɪt/", "zh": "单位", "pos": "n.", "ex": "The unit is small.", "cat": "general"},
  {"w": "use", "ipa": "/juːs/", "zh": "使用", "pos": "n.", "ex": "The use is clear.", "cat": "general"},
  {"w": "value", "ipa": "/ˈvæljuː/", "zh": "价值", "pos": "n.", "ex": "The value is high.", "cat": "general"},
  {"w": "verse", "ipa": "/vɜːrs/", "zh": "诗节", "pos": "n.", "ex": "He read a verse.", "cat": "general"},
  {"w": "vessel", "ipa": "/ˈvesl/", "zh": "容器", "pos": "n.", "ex": "The vessel is full.", "cat": "general"},
  {"w": "view", "ipa": "/vjuː/", "zh": "视图", "pos": "n.", "ex": "The view is nice.", "cat": "general"},
  {"w": "voice", "ipa": "/vɔɪs/", "zh": "声音", "pos": "n.", "ex": "Her voice is soft.", "cat": "general"},
  {"w": "walk", "ipa": "/wɔːk/", "zh": "散步", "pos": "n.", "ex": "He went for a walk.", "cat": "general"},
  {"w": "war", "ipa": "/wɔːr/", "zh": "战争", "pos": "n.", "ex": "The war is over.", "cat": "general"},
  {"w": "wash", "ipa": "/wɒʃ/", "zh": "洗涤", "pos": "n.", "ex": "The wash is done.", "cat": "general"},
  {"w": "waste", "ipa": "/weɪst/", "zh": "废物", "pos": "n.", "ex": "The waste is much.", "cat": "general"},
  {"w": "water", "ipa": "/ˈwɔːtər/", "zh": "水", "pos": "n.", "ex": "The water is cold.", "cat": "general"},
  {"w": "wave", "ipa": "/weɪv/", "zh": "波浪", "pos": "n.", "ex": "The wave is high.", "cat": "general"},
  {"w": "wax", "ipa": "/wæks/", "zh": "蜡", "pos": "n.", "ex": "The wax is melted.", "cat": "general"},
  {"w": "way", "ipa": "/weɪ/", "zh": "道路", "pos": "n.", "ex": "The way is long.", "cat": "general"},
  {"w": "weather", "ipa": "/ˈweðər/", "zh": "天气", "pos": "n.", "ex": "The weather is fine.", "cat": "general"},
  {"w": "week", "ipa": "/wiːk/", "zh": "周", "pos": "n.", "ex": "The week is busy.", "cat": "general"},
  {"w": "weight", "ipa": "/weɪt/", "zh": "重量", "pos": "n.", "ex": "The weight is heavy.", "cat": "general"},
  {"w": "wind", "ipa": "/wɪnd/", "zh": "风", "pos": "n.", "ex": "The wind is strong.", "cat": "general"},
  {"w": "wine", "ipa": "/waɪn/", "zh": "葡萄酒", "pos": "n.", "ex": "The wine is red.", "cat": "general"},
  {"w": "winter", "ipa": "/ˈwɪntər/", "zh": "冬天", "pos": "n.", "ex": "Winter is cold.", "cat": "general"},
  {"w": "woman", "ipa": "/ˈwʊmən/", "zh": "女人", "pos": "n.", "ex": "The woman is kind.", "cat": "general"},
  {"w": "wood", "ipa": "/wʊd/", "zh": "木头", "pos": "n.", "ex": "The wood is dry.", "cat": "general"},
  {"w": "wool", "ipa": "/wʊl/", "zh": "羊毛", "pos": "n.", "ex": "The wool is warm.", "cat": "general"},
  {"w": "word", "ipa": "/wɜːrd/", "zh": "单词", "pos": "n.", "ex": "The word is new.", "cat": "general"},
  {"w": "work", "ipa": "/wɜːrk/", "zh": "工作", "pos": "n.", "ex": "The work is hard.", "cat": "general"},
  {"w": "wound", "ipa": "/wuːnd/", "zh": "伤口", "pos": "n.", "ex": "The wound is deep.", "cat": "general"},
  {"w": "writing", "ipa": "/ˈraɪtɪŋ/", "zh": "写作", "pos": "n.", "ex": "The writing is clear.", "cat": "general"},
  {"w": "year", "ipa": "/jɪər/", "zh": "年", "pos": "n.", "ex": "The year is new.", "cat": "general"},
  {"w": "angle", "ipa": "/ˈæŋɡəl/", "zh": "角", "pos": "n.", "ex": "The angle is ninety degrees.", "cat": "thing"},
  {"w": "ant", "ipa": "/ænt/", "zh": "蚂蚁", "pos": "n.", "ex": "The ant is on the ground.", "cat": "thing"},
  {"w": "apple", "ipa": "/ˈæpəl/", "zh": "苹果", "pos": "n.", "ex": "He ate a red apple.", "cat": "thing"},
  {"w": "arch", "ipa": "/ɑːrtʃ/", "zh": "拱门", "pos": "n.", "ex": "The arch is very old.", "cat": "thing"},
  {"w": "arm", "ipa": "/ɑːrm/", "zh": "手臂", "pos": "n.", "ex": "His arm is strong.", "cat": "thing"},
  {"w": "army", "ipa": "/ˈɑːrmi/", "zh": "军队", "pos": "n.", "ex": "The army marched away.", "cat": "thing"},
  {"w": "baby", "ipa": "/ˈbeɪbi/", "zh": "婴儿", "pos": "n.", "ex": "The baby is crying.", "cat": "thing"},
  {"w": "bag", "ipa": "/bæɡ/", "zh": "袋子", "pos": "n.", "ex": "She carried a bag.", "cat": "thing"},
  {"w": "ball", "ipa": "/bɔːl/", "zh": "球", "pos": "n.", "ex": "The ball is round.", "cat": "thing"},
  {"w": "band", "ipa": "/bænd/", "zh": "带子", "pos": "n.", "ex": "He wore a rubber band.", "cat": "thing"},
  {"w": "basin", "ipa": "/ˈbeɪsən/", "zh": "盆", "pos": "n.", "ex": "The basin is full.", "cat": "thing"},
  {"w": "basket", "ipa": "/ˈbɑːskɪt/", "zh": "篮子", "pos": "n.", "ex": "She made a basket.", "cat": "thing"},
  {"w": "bath", "ipa": "/bæθ/", "zh": "浴缸", "pos": "n.", "ex": "He took a bath.", "cat": "thing"},
  {"w": "bed", "ipa": "/bed/", "zh": "床", "pos": "n.", "ex": "The bed is soft.", "cat": "thing"},
  {"w": "bee", "ipa": "/biː/", "zh": "蜜蜂", "pos": "n.", "ex": "A bee flew by.", "cat": "thing"},
  {"w": "bell", "ipa": "/bel/", "zh": "铃", "pos": "n.", "ex": "The bell rang loud.", "cat": "thing"},
  {"w": "berry", "ipa": "/ˈberi/", "zh": "浆果", "pos": "n.", "ex": "She ate a berry.", "cat": "thing"},
  {"w": "bird", "ipa": "/bɜːrd/", "zh": "鸟", "pos": "n.", "ex": "The bird can sing.", "cat": "thing"},
  {"w": "blade", "ipa": "/bleɪd/", "zh": "刀片", "pos": "n.", "ex": "The blade is sharp.", "cat": "thing"},
  {"w": "board", "ipa": "/bɔːrd/", "zh": "木板", "pos": "n.", "ex": "He cut the board.", "cat": "thing"},
  {"w": "boat", "ipa": "/boʊt/", "zh": "船", "pos": "n.", "ex": "The boat is small.", "cat": "thing"},
  {"w": "bone", "ipa": "/boʊn/", "zh": "骨头", "pos": "n.", "ex": "The dog ate a bone.", "cat": "thing"},
  {"w": "book", "ipa": "/bʊk/", "zh": "书", "pos": "n.", "ex": "She read a book.", "cat": "thing"},
  {"w": "boot", "ipa": "/buːt/", "zh": "靴子", "pos": "n.", "ex": "He wore a boot.", "cat": "thing"},
  {"w": "bottle", "ipa": "/ˈbɑːtl/", "zh": "瓶子", "pos": "n.", "ex": "The bottle is empty.", "cat": "thing"},
  {"w": "box", "ipa": "/bɑːks/", "zh": "盒子", "pos": "n.", "ex": "He opened the box.", "cat": "thing"},
  {"w": "boy", "ipa": "/bɔɪ/", "zh": "男孩", "pos": "n.", "ex": "The boy is tall.", "cat": "thing"},
  {"w": "brain", "ipa": "/breɪn/", "zh": "大脑", "pos": "n.", "ex": "The brain is vital.", "cat": "thing"},
  {"w": "brake", "ipa": "/breɪk/", "zh": "刹车", "pos": "n.", "ex": "He used the brake.", "cat": "thing"},
  {"w": "branch", "ipa": "/brɑːntʃ/", "zh": "树枝", "pos": "n.", "ex": "The branch broke off.", "cat": "thing"},
  {"w": "brick", "ipa": "/brɪk/", "zh": "砖", "pos": "n.", "ex": "The wall is brick.", "cat": "thing"},
  {"w": "bridge", "ipa": "/brɪdʒ/", "zh": "桥", "pos": "n.", "ex": "We crossed the bridge.", "cat": "thing"},
  {"w": "brush", "ipa": "/brʌʃ/", "zh": "刷子", "pos": "n.", "ex": "She used a brush.", "cat": "thing"},
  {"w": "bucket", "ipa": "/ˈbʌkɪt/", "zh": "桶", "pos": "n.", "ex": "He filled the bucket.", "cat": "thing"},
  {"w": "bulb", "ipa": "/bʌlb/", "zh": "灯泡", "pos": "n.", "ex": "The bulb is bright.", "cat": "thing"},
  {"w": "button", "ipa": "/ˈbʌtn/", "zh": "按钮", "pos": "n.", "ex": "Press the button now.", "cat": "thing"},
  {"w": "cake", "ipa": "/keɪk/", "zh": "蛋糕", "pos": "n.", "ex": "She baked a cake.", "cat": "thing"},
  {"w": "camera", "ipa": "/ˈkæmərə/", "zh": "照相机", "pos": "n.", "ex": "He bought a camera.", "cat": "thing"},
  {"w": "card", "ipa": "/kɑːrd/", "zh": "卡片", "pos": "n.", "ex": "I sent a card.", "cat": "thing"},
  {"w": "cart", "ipa": "/kɑːrt/", "zh": "手推车", "pos": "n.", "ex": "The cart is old.", "cat": "thing"},
  {"w": "carriage", "ipa": "/ˈkærɪdʒ/", "zh": "马车", "pos": "n.", "ex": "The carriage is black.", "cat": "thing"},
  {"w": "cat", "ipa": "/kæt/", "zh": "猫", "pos": "n.", "ex": "The cat is sleeping.", "cat": "thing"},
  {"w": "chain", "ipa": "/tʃeɪn/", "zh": "链条", "pos": "n.", "ex": "He pulled the chain.", "cat": "thing"},
  {"w": "cheese", "ipa": "/tʃiːz/", "zh": "奶酪", "pos": "n.", "ex": "We ate the cheese.", "cat": "thing"},
  {"w": "chest", "ipa": "/tʃest/", "zh": "胸膛", "pos": "n.", "ex": "His chest is broad.", "cat": "thing"},
  {"w": "chin", "ipa": "/tʃɪn/", "zh": "下巴", "pos": "n.", "ex": "He touched his chin.", "cat": "thing"},
  {"w": "church", "ipa": "/tʃɜːrtʃ/", "zh": "教堂", "pos": "n.", "ex": "They entered the church.", "cat": "thing"},
  {"w": "circle", "ipa": "/ˈsɜːrkl/", "zh": "圆", "pos": "n.", "ex": "Draw a circle please.", "cat": "thing"},
  {"w": "clock", "ipa": "/klɑːk/", "zh": "时钟", "pos": "n.", "ex": "The clock is slow.", "cat": "thing"},
  {"w": "cloud", "ipa": "/klaʊd/", "zh": "云", "pos": "n.", "ex": "The cloud is white.", "cat": "thing"},
  {"w": "coat", "ipa": "/koʊt/", "zh": "外套", "pos": "n.", "ex": "He wore a coat.", "cat": "thing"},
  {"w": "collar", "ipa": "/ˈkɑːlər/", "zh": "衣领", "pos": "n.", "ex": "The collar is clean.", "cat": "thing"},
  {"w": "comb", "ipa": "/koʊm/", "zh": "梳子", "pos": "n.", "ex": "She lost her comb.", "cat": "thing"},
  {"w": "cord", "ipa": "/kɔːrd/", "zh": "绳子", "pos": "n.", "ex": "He tied the cord.", "cat": "thing"},
  {"w": "cow", "ipa": "/kaʊ/", "zh": "奶牛", "pos": "n.", "ex": "The cow is brown.", "cat": "thing"},
  {"w": "cup", "ipa": "/kʌp/", "zh": "杯子", "pos": "n.", "ex": "She drank from cup.", "cat": "thing"},
  {"w": "curtain", "ipa": "/ˈkɜːrtn/", "zh": "窗帘", "pos": "n.", "ex": "The curtain is blue.", "cat": "thing"},
  {"w": "cushion", "ipa": "/ˈkʊʃn/", "zh": "垫子", "pos": "n.", "ex": "He sat on cushion.", "cat": "thing"},
  {"w": "dog", "ipa": "/dɔːɡ/", "zh": "狗", "pos": "n.", "ex": "The dog is friendly.", "cat": "thing"},
  {"w": "door", "ipa": "/dɔːr/", "zh": "门", "pos": "n.", "ex": "She opened the door.", "cat": "thing"},
  {"w": "drain", "ipa": "/dreɪn/", "zh": "排水管", "pos": "n.", "ex": "The drain is blocked.", "cat": "thing"},
  {"w": "drawer", "ipa": "/drɔːr/", "zh": "抽屉", "pos": "n.", "ex": "He shut the drawer.", "cat": "thing"},
  {"w": "dress", "ipa": "/dres/", "zh": "连衣裙", "pos": "n.", "ex": "She wore a dress.", "cat": "thing"},
  {"w": "drop", "ipa": "/drɑːp/", "zh": "水滴", "pos": "n.", "ex": "A drop fell down.", "cat": "thing"},
  {"w": "ear", "ipa": "/ɪr/", "zh": "耳朵", "pos": "n.", "ex": "His ear is small.", "cat": "thing"},
  {"w": "egg", "ipa": "/eɡ/", "zh": "蛋", "pos": "n.", "ex": "The egg is white.", "cat": "thing"},
  {"w": "engine", "ipa": "/ˈendʒɪn/", "zh": "引擎", "pos": "n.", "ex": "The engine is loud.", "cat": "thing"},
  {"w": "eye", "ipa": "/aɪ/", "zh": "眼睛", "pos": "n.", "ex": "Her eye is blue.", "cat": "thing"},
  {"w": "face", "ipa": "/feɪs/", "zh": "脸", "pos": "n.", "ex": "He washed his face.", "cat": "thing"},
  {"w": "farm", "ipa": "/fɑːrm/", "zh": "农场", "pos": "n.", "ex": "The farm is big.", "cat": "thing"},
  {"w": "feather", "ipa": "/ˈfeðər/", "zh": "羽毛", "pos": "n.", "ex": "The feather is light.", "cat": "thing"},
  {"w": "finger", "ipa": "/ˈfɪŋɡər/", "zh": "手指", "pos": "n.", "ex": "She cut her finger.", "cat": "thing"},
  {"w": "fish", "ipa": "/fɪʃ/", "zh": "鱼", "pos": "n.", "ex": "The fish is swimming.", "cat": "thing"},
  {"w": "flag", "ipa": "/flæɡ/", "zh": "旗帜", "pos": "n.", "ex": "The flag is red.", "cat": "thing"},
  {"w": "floor", "ipa": "/flɔːr/", "zh": "地板", "pos": "n.", "ex": "The floor is clean.", "cat": "thing"},
  {"w": "fly", "ipa": "/flaɪ/", "zh": "苍蝇", "pos": "n.", "ex": "A fly is buzzing.", "cat": "thing"},
  {"w": "foot", "ipa": "/fʊt/", "zh": "脚", "pos": "n.", "ex": "His foot is hurt.", "cat": "thing"},
  {"w": "fork", "ipa": "/fɔːrk/", "zh": "叉子", "pos": "n.", "ex": "He used a fork.", "cat": "thing"},
  {"w": "fowl", "ipa": "/faʊl/", "zh": "家禽", "pos": "n.", "ex": "The fowl ate corn.", "cat": "thing"},
  {"w": "frame", "ipa": "/freɪm/", "zh": "框架", "pos": "n.", "ex": "The frame is wooden.", "cat": "thing"},
  {"w": "garden", "ipa": "/ˈɡɑːrdn/", "zh": "花园", "pos": "n.", "ex": "The garden is pretty.", "cat": "thing"},
  {"w": "girl", "ipa": "/ɡɜːrl/", "zh": "女孩", "pos": "n.", "ex": "The girl is laughing.", "cat": "thing"},
  {"w": "glove", "ipa": "/ɡlʌv/", "zh": "手套", "pos": "n.", "ex": "He lost a glove.", "cat": "thing"},
  {"w": "goat", "ipa": "/ɡoʊt/", "zh": "山羊", "pos": "n.", "ex": "The goat is hungry.", "cat": "thing"},
  {"w": "gun", "ipa": "/ɡʌn/", "zh": "枪", "pos": "n.", "ex": "He aimed the gun.", "cat": "thing"},
  {"w": "hair", "ipa": "/her/", "zh": "头发", "pos": "n.", "ex": "Her hair is long.", "cat": "thing"},
  {"w": "hammer", "ipa": "/ˈhæmər/", "zh": "锤子", "pos": "n.", "ex": "He used a hammer.", "cat": "thing"},
  {"w": "hand", "ipa": "/hænd/", "zh": "手", "pos": "n.", "ex": "His hand is warm.", "cat": "thing"},
  {"w": "hat", "ipa": "/hæt/", "zh": "帽子", "pos": "n.", "ex": "She wore a hat.", "cat": "thing"},
  {"w": "head", "ipa": "/hed/", "zh": "头", "pos": "n.", "ex": "His head is aching.", "cat": "thing"},
  {"w": "heart", "ipa": "/hɑːrt/", "zh": "心脏", "pos": "n.", "ex": "The heart is beating.", "cat": "thing"},
  {"w": "hook", "ipa": "/hʊk/", "zh": "钩子", "pos": "n.", "ex": "He hung the hook.", "cat": "thing"},
  {"w": "horn", "ipa": "/hɔːrn/", "zh": "角", "pos": "n.", "ex": "The ox has horn.", "cat": "thing"},
  {"w": "horse", "ipa": "/hɔːrs/", "zh": "马", "pos": "n.", "ex": "The horse ran fast.", "cat": "thing"},
  {"w": "hospital", "ipa": "/ˈhɑːspɪtl/", "zh": "医院", "pos": "n.", "ex": "She went to hospital.", "cat": "thing"},
  {"w": "house", "ipa": "/haʊs/", "zh": "房子", "pos": "n.", "ex": "The house is white.", "cat": "thing"},
  {"w": "island", "ipa": "/ˈaɪlənd/", "zh": "岛屿", "pos": "n.", "ex": "The island is small.", "cat": "thing"},
  {"w": "jewel", "ipa": "/ˈdʒuːəl/", "zh": "宝石", "pos": "n.", "ex": "She wore a jewel.", "cat": "thing"},
  {"w": "kettle", "ipa": "/ˈketl/", "zh": "水壶", "pos": "n.", "ex": "The kettle is boiling.", "cat": "thing"},
  {"w": "key", "ipa": "/kiː/", "zh": "钥匙", "pos": "n.", "ex": "He lost the key.", "cat": "thing"},
  {"w": "knee", "ipa": "/niː/", "zh": "膝盖", "pos": "n.", "ex": "His knee is sore.", "cat": "thing"},
  {"w": "knife", "ipa": "/naɪf/", "zh": "刀", "pos": "n.", "ex": "The knife is sharp.", "cat": "thing"},
  {"w": "knot", "ipa": "/nɑːt/", "zh": "结", "pos": "n.", "ex": "He tied a knot.", "cat": "thing"},
  {"w": "leaf", "ipa": "/liːf/", "zh": "叶子", "pos": "n.", "ex": "The leaf is green.", "cat": "thing"},
  {"w": "leg", "ipa": "/leɡ/", "zh": "腿", "pos": "n.", "ex": "Her leg is broken.", "cat": "thing"},
  {"w": "library", "ipa": "/ˈlaɪbreri/", "zh": "图书馆", "pos": "n.", "ex": "The library is quiet.", "cat": "thing"},
  {"w": "line", "ipa": "/laɪn/", "zh": "线", "pos": "n.", "ex": "Draw a straight line.", "cat": "thing"},
  {"w": "lip", "ipa": "/lɪp/", "zh": "嘴唇", "pos": "n.", "ex": "Her lip is cut.", "cat": "thing"},
  {"w": "lock", "ipa": "/lɑːk/", "zh": "锁", "pos": "n.", "ex": "He opened the lock.", "cat": "thing"},
  {"w": "map", "ipa": "/mæp/", "zh": "地图", "pos": "n.", "ex": "She read the map.", "cat": "thing"},
  {"w": "match", "ipa": "/mætʃ/", "zh": "火柴", "pos": "n.", "ex": "He lit a match.", "cat": "thing"},
  {"w": "monkey", "ipa": "/ˈmʌŋki/", "zh": "猴子", "pos": "n.", "ex": "The monkey is funny.", "cat": "thing"},
  {"w": "moon", "ipa": "/muːn/", "zh": "月亮", "pos": "n.", "ex": "The moon is bright.", "cat": "thing"},
  {"w": "mouth", "ipa": "/maʊθ/", "zh": "嘴", "pos": "n.", "ex": "His mouth is full.", "cat": "thing"},
  {"w": "muscle", "ipa": "/ˈmʌsl/", "zh": "肌肉", "pos": "n.", "ex": "The muscle is sore.", "cat": "thing"},
  {"w": "nail", "ipa": "/neɪl/", "zh": "钉子", "pos": "n.", "ex": "He hit the nail.", "cat": "thing"},
  {"w": "neck", "ipa": "/nek/", "zh": "脖子", "pos": "n.", "ex": "Her neck is long.", "cat": "thing"},
  {"w": "needle", "ipa": "/ˈniːdl/", "zh": "针", "pos": "n.", "ex": "She threaded the needle.", "cat": "thing"},
  {"w": "nerve", "ipa": "/nɜːrv/", "zh": "神经", "pos": "n.", "ex": "The nerve is damaged.", "cat": "thing"},
  {"w": "net", "ipa": "/net/", "zh": "网", "pos": "n.", "ex": "He cast the net.", "cat": "thing"},
  {"w": "nose", "ipa": "/noʊz/", "zh": "鼻子", "pos": "n.", "ex": "His nose is red.", "cat": "thing"},
  {"w": "nut", "ipa": "/nʌt/", "zh": "坚果", "pos": "n.", "ex": "She ate a nut.", "cat": "thing"},
  {"w": "office", "ipa": "/ˈɔːfɪs/", "zh": "办公室", "pos": "n.", "ex": "He left the office.", "cat": "thing"},
  {"w": "orange", "ipa": "/ˈɔːrɪndʒ/", "zh": "橙子", "pos": "n.", "ex": "She peeled the orange.", "cat": "thing"},
  {"w": "oven", "ipa": "/ˈʌvn/", "zh": "烤箱", "pos": "n.", "ex": "The oven is hot.", "cat": "thing"},
  {"w": "parcel", "ipa": "/ˈpɑːrsl/", "zh": "包裹", "pos": "n.", "ex": "He sent a parcel.", "cat": "thing"},
  {"w": "pen", "ipa": "/pen/", "zh": "钢笔", "pos": "n.", "ex": "She wrote with pen.", "cat": "thing"},
  {"w": "pencil", "ipa": "/ˈpensl/", "zh": "铅笔", "pos": "n.", "ex": "He used a pencil.", "cat": "thing"},
  {"w": "picture", "ipa": "/ˈpɪktʃər/", "zh": "图画", "pos": "n.", "ex": "The picture is nice.", "cat": "thing"},
  {"w": "pig", "ipa": "/pɪɡ/", "zh": "猪", "pos": "n.", "ex": "The pig is pink.", "cat": "thing"},
  {"w": "pin", "ipa": "/pɪn/", "zh": "别针", "pos": "n.", "ex": "She used a pin.", "cat": "thing"},
  {"w": "pipe", "ipa": "/paɪp/", "zh": "管子", "pos": "n.", "ex": "The pipe is leaking.", "cat": "thing"},
  {"w": "plane", "ipa": "/pleɪn/", "zh": "飞机", "pos": "n.", "ex": "The plane flew high.", "cat": "thing"},
  {"w": "plate", "ipa": "/pleɪt/", "zh": "盘子", "pos": "n.", "ex": "He dropped the plate.", "cat": "thing"},
  {"w": "plough", "ipa": "/plaʊ/", "zh": "犁", "pos": "n.", "ex": "The plough is old.", "cat": "thing"},
  {"w": "pocket", "ipa": "/ˈpɑːkɪt/", "zh": "口袋", "pos": "n.", "ex": "He put it in pocket.", "cat": "thing"},
  {"w": "pot", "ipa": "/pɑːt/", "zh": "锅", "pos": "n.", "ex": "The pot is full.", "cat": "thing"},
  {"w": "potato", "ipa": "/pəˈteɪtoʊ/", "zh": "土豆", "pos": "n.", "ex": "I ate a potato for lunch.", "cat": "thing"},
  {"w": "prison", "ipa": "/ˈprɪzən/", "zh": "监狱", "pos": "n.", "ex": "The prison is very old.", "cat": "thing"},
  {"w": "pump", "ipa": "/pʌmp/", "zh": "泵", "pos": "n.", "ex": "He used a pump to get water.", "cat": "thing"},
  {"w": "rail", "ipa": "/reɪl/", "zh": "铁轨", "pos": "n.", "ex": "The train is on the rail.", "cat": "thing"},
  {"w": "rat", "ipa": "/ræt/", "zh": "老鼠", "pos": "n.", "ex": "A rat ran across the floor.", "cat": "thing"},
  {"w": "receipt", "ipa": "/rɪˈsiːt/", "zh": "收据", "pos": "n.", "ex": "She kept the receipt for me.", "cat": "thing"},
  {"w": "ring", "ipa": "/rɪŋ/", "zh": "戒指", "pos": "n.", "ex": "He gave her a gold ring.", "cat": "thing"},
  {"w": "rod", "ipa": "/rɒd/", "zh": "杆", "pos": "n.", "ex": "The fisherman held a rod.", "cat": "thing"},
  {"w": "roof", "ipa": "/ruːf/", "zh": "屋顶", "pos": "n.", "ex": "The roof is made of wood.", "cat": "thing"},
  {"w": "root", "ipa": "/ruːt/", "zh": "根", "pos": "n.", "ex": "The tree has a long root.", "cat": "thing"},
  {"w": "sail", "ipa": "/seɪl/", "zh": "帆", "pos": "n.", "ex": "The boat has a white sail.", "cat": "thing"},
  {"w": "school", "ipa": "/skuːl/", "zh": "学校", "pos": "n.", "ex": "Children go to school daily.", "cat": "thing"},
  {"w": "scissors", "ipa": "/ˈsɪzərz/", "zh": "剪刀", "pos": "n.", "ex": "She cut paper with scissors.", "cat": "thing"},
  {"w": "screw", "ipa": "/skruː/", "zh": "螺丝", "pos": "n.", "ex": "He turned the screw with care.", "cat": "thing"},
  {"w": "seed", "ipa": "/siːd/", "zh": "种子", "pos": "n.", "ex": "I planted a seed in soil.", "cat": "thing"},
  {"w": "sheep", "ipa": "/ʃiːp/", "zh": "绵羊", "pos": "n.", "ex": "The sheep ate green grass.", "cat": "thing"},
  {"w": "shelf", "ipa": "/ʃelf/", "zh": "架子", "pos": "n.", "ex": "The book is on the shelf.", "cat": "thing"},
  {"w": "ship", "ipa": "/ʃɪp/", "zh": "船", "pos": "n.", "ex": "The ship sailed on the sea.", "cat": "thing"},
  {"w": "shirt", "ipa": "/ʃɜːrt/", "zh": "衬衫", "pos": "n.", "ex": "He wore a clean shirt.", "cat": "thing"},
  {"w": "shoe", "ipa": "/ʃuː/", "zh": "鞋", "pos": "n.", "ex": "My shoe is under the bed.", "cat": "thing"},
  {"w": "skin", "ipa": "/skɪn/", "zh": "皮肤", "pos": "n.", "ex": "The baby has soft skin.", "cat": "thing"},
  {"w": "skirt", "ipa": "/skɜːrt/", "zh": "裙子", "pos": "n.", "ex": "She bought a red skirt.", "cat": "thing"},
  {"w": "snake", "ipa": "/sneɪk/", "zh": "蛇", "pos": "n.", "ex": "A snake lay in the sun.", "cat": "thing"},
  {"w": "sock", "ipa": "/sɒk/", "zh": "袜子", "pos": "n.", "ex": "One sock is lost again.", "cat": "thing"},
  {"w": "spade", "ipa": "/speɪd/", "zh": "铲子", "pos": "n.", "ex": "He dug with a spade.", "cat": "thing"},
  {"w": "sponge", "ipa": "/spʌndʒ/", "zh": "海绵", "pos": "n.", "ex": "She cleaned with a sponge.", "cat": "thing"},
  {"w": "spoon", "ipa": "/spuːn/", "zh": "勺子", "pos": "n.", "ex": "He ate soup with a spoon.", "cat": "thing"},
  {"w": "spring", "ipa": "/sprɪŋ/", "zh": "春天", "pos": "n.", "ex": "Spring brings warm weather.", "cat": "thing"},
  {"w": "square", "ipa": "/skweər/", "zh": "正方形", "pos": "n.", "ex": "The tile is a square.", "cat": "thing"},
  {"w": "stamp", "ipa": "/stæmp/", "zh": "邮票", "pos": "n.", "ex": "I put a stamp on it.", "cat": "thing"},
  {"w": "star", "ipa": "/stɑːr/", "zh": "星星", "pos": "n.", "ex": "A star shone at night.", "cat": "thing"},
  {"w": "station", "ipa": "/ˈsteɪʃən/", "zh": "车站", "pos": "n.", "ex": "He waited at the station.", "cat": "thing"},
  {"w": "stem", "ipa": "/stem/", "zh": "茎", "pos": "n.", "ex": "The flower has a green stem.", "cat": "thing"},
  {"w": "stick", "ipa": "/stɪk/", "zh": "棍子", "pos": "n.", "ex": "He found a long stick.", "cat": "thing"},
  {"w": "stocking", "ipa": "/ˈstɒkɪŋ/", "zh": "长袜", "pos": "n.", "ex": "She wore a wool stocking.", "cat": "thing"},
  {"w": "stomach", "ipa": "/ˈstʌmək/", "zh": "胃", "pos": "n.", "ex": "My stomach feels very full.", "cat": "thing"},
  {"w": "street", "ipa": "/striːt/", "zh": "街道", "pos": "n.", "ex": "The street is wide and clean.", "cat": "thing"},
  {"w": "sun", "ipa": "/sʌn/", "zh": "太阳", "pos": "n.", "ex": "The sun is very bright.", "cat": "thing"},
  {"w": "table", "ipa": "/ˈteɪbəl/", "zh": "桌子", "pos": "n.", "ex": "The book is on the table.", "cat": "thing"},
  {"w": "tail", "ipa": "/teɪl/", "zh": "尾巴", "pos": "n.", "ex": "The dog wagged its tail.", "cat": "thing"},
  {"w": "thread", "ipa": "/θred/", "zh": "线", "pos": "n.", "ex": "She sewed with red thread.", "cat": "thing"},
  {"w": "throat", "ipa": "/θroʊt/", "zh": "喉咙", "pos": "n.", "ex": "His throat hurts today.", "cat": "thing"},
  {"w": "thumb", "ipa": "/θʌm/", "zh": "拇指", "pos": "n.", "ex": "She sucked her thumb.", "cat": "thing"},
  {"w": "ticket", "ipa": "/ˈtɪkɪt/", "zh": "票", "pos": "n.", "ex": "I lost my train ticket.", "cat": "thing"},
  {"w": "toe", "ipa": "/toʊ/", "zh": "脚趾", "pos": "n.", "ex": "He stepped on my toe.", "cat": "thing"},
  {"w": "tongue", "ipa": "/tʌŋ/", "zh": "舌头", "pos": "n.", "ex": "The child bit its tongue.", "cat": "thing"},
  {"w": "tooth", "ipa": "/tuːθ/", "zh": "牙齿", "pos": "n.", "ex": "He brushed his tooth.", "cat": "thing"},
  {"w": "town", "ipa": "/taʊn/", "zh": "城镇", "pos": "n.", "ex": "We live in a small town.", "cat": "thing"},
  {"w": "train", "ipa": "/treɪn/", "zh": "火车", "pos": "n.", "ex": "The train is coming now.", "cat": "thing"},
  {"w": "tray", "ipa": "/treɪ/", "zh": "托盘", "pos": "n.", "ex": "She carried a full tray.", "cat": "thing"},
  {"w": "tree", "ipa": "/triː/", "zh": "树", "pos": "n.", "ex": "The tree is very tall.", "cat": "thing"},
  {"w": "trousers", "ipa": "/ˈtraʊzərz/", "zh": "裤子", "pos": "n.", "ex": "He wore old trousers.", "cat": "thing"},
  {"w": "umbrella", "ipa": "/ʌmˈbrelə/", "zh": "雨伞", "pos": "n.", "ex": "She opened her umbrella.", "cat": "thing"},
  {"w": "wall", "ipa": "/wɔːl/", "zh": "墙", "pos": "n.", "ex": "The wall is painted white.", "cat": "thing"},
  {"w": "watch", "ipa": "/wɒtʃ/", "zh": "手表", "pos": "n.", "ex": "He looked at his watch.", "cat": "thing"},
  {"w": "wheel", "ipa": "/wiːl/", "zh": "轮子", "pos": "n.", "ex": "The wheel turned very fast.", "cat": "thing"},
  {"w": "whip", "ipa": "/wɪp/", "zh": "鞭子", "pos": "n.", "ex": "He cracked the long whip.", "cat": "thing"},
  {"w": "whistle", "ipa": "/ˈwɪsəl/", "zh": "哨子", "pos": "n.", "ex": "The man blew a whistle.", "cat": "thing"},
  {"w": "window", "ipa": "/ˈwɪndoʊ/", "zh": "窗户", "pos": "n.", "ex": "She closed the window.", "cat": "thing"},
  {"w": "wing", "ipa": "/wɪŋ/", "zh": "翅膀", "pos": "n.", "ex": "The bird has one wing.", "cat": "thing"},
  {"w": "wire", "ipa": "/ˈwaɪər/", "zh": "电线", "pos": "n.", "ex": "The wire is very thin.", "cat": "thing"},
  {"w": "worm", "ipa": "/wɜːrm/", "zh": "蠕虫", "pos": "n.", "ex": "A worm crawled on soil.", "cat": "thing"},
  {"w": "store", "ipa": "/stɔːr/", "zh": "商店", "pos": "n.", "ex": "I bought milk at the store.", "cat": "thing"},
  {"w": "able", "ipa": "/ˈeɪbəl/", "zh": "有能力的", "pos": "adj.", "ex": "The boy is able to swim.", "cat": "adjective"},
  {"w": "acid", "ipa": "/ˈæsɪd/", "zh": "酸的", "pos": "adj.", "ex": "The acid taste is strong.", "cat": "adjective"},
  {"w": "angry", "ipa": "/ˈæŋɡri/", "zh": "生气的", "pos": "adj.", "ex": "The man is angry now.", "cat": "adjective"},
  {"w": "automatic", "ipa": "/ˌɔːtəˈmætɪk/", "zh": "自动的", "pos": "adj.", "ex": "The door is automatic.", "cat": "adjective"},
  {"w": "beautiful", "ipa": "/ˈbjuːtɪfəl/", "zh": "美丽的", "pos": "adj.", "ex": "She is a beautiful girl.", "cat": "adjective"},
  {"w": "black", "ipa": "/blæk/", "zh": "黑色的", "pos": "adj.", "ex": "The cat is black.", "cat": "adjective"},
  {"w": "boiling", "ipa": "/ˈbɔɪlɪŋ/", "zh": "沸腾的", "pos": "adj.", "ex": "The water is boiling.", "cat": "adjective"},
  {"w": "bright", "ipa": "/braɪt/", "zh": "明亮的", "pos": "adj.", "ex": "The sun is bright.", "cat": "adjective"},
  {"w": "broken", "ipa": "/ˈbroʊkən/", "zh": "破损的", "pos": "adj.", "ex": "The cup is broken.", "cat": "adjective"},
  {"w": "brown", "ipa": "/braʊn/", "zh": "棕色的", "pos": "adj.", "ex": "The dog is brown.", "cat": "adjective"},
  {"w": "cheap", "ipa": "/tʃiːp/", "zh": "便宜的", "pos": "adj.", "ex": "The book is cheap.", "cat": "adjective"},
  {"w": "chemical", "ipa": "/ˈkemɪkəl/", "zh": "化学的", "pos": "adj.", "ex": "This is a chemical change.", "cat": "adjective"},
  {"w": "chief", "ipa": "/tʃiːf/", "zh": "主要的", "pos": "adj.", "ex": "He is the chief man.", "cat": "adjective"},
  {"w": "clean", "ipa": "/kliːn/", "zh": "干净的", "pos": "adj.", "ex": "The room is clean.", "cat": "adjective"},
  {"w": "clear", "ipa": "/klɪr/", "zh": "清晰的", "pos": "adj.", "ex": "The glass is clear.", "cat": "adjective"},
  {"w": "common", "ipa": "/ˈkɒmən/", "zh": "常见的", "pos": "adj.", "ex": "This is a common bird.", "cat": "adjective"},
  {"w": "complex", "ipa": "/ˈkɒmpleks/", "zh": "复杂的", "pos": "adj.", "ex": "The task is complex.", "cat": "adjective"},
  {"w": "conscious", "ipa": "/ˈkɒnʃəs/", "zh": "清醒的", "pos": "adj.", "ex": "She is conscious now.", "cat": "adjective"},
  {"w": "cut", "ipa": "/kʌt/", "zh": "切开的", "pos": "adj.", "ex": "The cut paper is small.", "cat": "adjective"},
  {"w": "deep", "ipa": "/diːp/", "zh": "深的", "pos": "adj.", "ex": "The well is deep.", "cat": "adjective"},
  {"w": "dependent", "ipa": "/dɪˈpendənt/", "zh": "依赖的", "pos": "adj.", "ex": "The child is dependent.", "cat": "adjective"},
  {"w": "early", "ipa": "/ˈɜːrli/", "zh": "早的", "pos": "adj.", "ex": "We are early today.", "cat": "adjective"},
  {"w": "elastic", "ipa": "/ɪˈlæstɪk/", "zh": "弹性的", "pos": "adj.", "ex": "The band is elastic.", "cat": "adjective"},
  {"w": "electric", "ipa": "/ɪˈlektrɪk/", "zh": "电的", "pos": "adj.", "ex": "The light is electric.", "cat": "adjective"},
  {"w": "equal", "ipa": "/ˈiːkwəl/", "zh": "相等的", "pos": "adj.", "ex": "The lines are equal.", "cat": "adjective"},
  {"w": "fat", "ipa": "/fæt/", "zh": "胖的", "pos": "adj.", "ex": "The pig is fat.", "cat": "adjective"},
  {"w": "fertile", "ipa": "/ˈfɜːrtaɪl/", "zh": "肥沃的", "pos": "adj.", "ex": "The soil is fertile.", "cat": "adjective"},
  {"w": "first", "ipa": "/fɜːrst/", "zh": "第一的", "pos": "adj.", "ex": "He won first prize.", "cat": "adjective"},
  {"w": "fixed", "ipa": "/fɪkst/", "zh": "固定的", "pos": "adj.", "ex": "The price is fixed.", "cat": "adjective"},
  {"w": "flat", "ipa": "/flæt/", "zh": "平坦的", "pos": "adj.", "ex": "The road is flat.", "cat": "adjective"},
  {"w": "free", "ipa": "/friː/", "zh": "自由的", "pos": "adj.", "ex": "The bird is free.", "cat": "adjective"},
  {"w": "frequent", "ipa": "/ˈfriːkwənt/", "zh": "频繁的", "pos": "adj.", "ex": "His visits are frequent.", "cat": "adjective"},
  {"w": "full", "ipa": "/fʊl/", "zh": "满的", "pos": "adj.", "ex": "The bottle is full.", "cat": "adjective"},
  {"w": "general", "ipa": "/ˈdʒenrəl/", "zh": "一般的", "pos": "adj.", "ex": "This is general knowledge.", "cat": "adjective"},
  {"w": "good", "ipa": "/ɡʊd/", "zh": "好的", "pos": "adj.", "ex": "The food is good.", "cat": "adjective"},
  {"w": "great", "ipa": "/ɡreɪt/", "zh": "伟大的", "pos": "adj.", "ex": "He is a great man.", "cat": "adjective"},
  {"w": "grey", "ipa": "/ɡreɪ/", "zh": "灰色的", "pos": "adj.", "ex": "The sky is grey.", "cat": "adjective"},
  {"w": "hanging", "ipa": "/ˈhæŋɪŋ/", "zh": "悬挂的", "pos": "adj.", "ex": "The lamp is hanging.", "cat": "adjective"},
  {"w": "happy", "ipa": "/ˈhæpi/", "zh": "快乐的", "pos": "adj.", "ex": "The child is happy.", "cat": "adjective"},
  {"w": "hard", "ipa": "/hɑːrd/", "zh": "硬的", "pos": "adj.", "ex": "The stone is hard.", "cat": "adjective"},
  {"w": "healthy", "ipa": "/ˈhelθi/", "zh": "健康的", "pos": "adj.", "ex": "She is a healthy woman.", "cat": "adjective"},
  {"w": "high", "ipa": "/haɪ/", "zh": "高的", "pos": "adj.", "ex": "The mountain is high.", "cat": "adjective"},
  {"w": "hollow", "ipa": "/ˈhɒloʊ/", "zh": "空的", "pos": "adj.", "ex": "The tree is hollow.", "cat": "adjective"},
  {"w": "important", "ipa": "/ɪmˈpɔːrtənt/", "zh": "重要的", "pos": "adj.", "ex": "This is an important day.", "cat": "adjective"},
  {"w": "kind", "ipa": "/kaɪnd/", "zh": "善良的", "pos": "adj.", "ex": "She is a kind lady.", "cat": "adjective"},
  {"w": "like", "ipa": "/laɪk/", "zh": "相似的", "pos": "adj.", "ex": "He is like his father.", "cat": "adjective"},
  {"w": "living", "ipa": "/ˈlɪvɪŋ/", "zh": "活着的", "pos": "adj.", "ex": "The plant is living.", "cat": "adjective"},
  {"w": "long", "ipa": "/lɔːŋ/", "zh": "长的", "pos": "adj.", "ex": "The rope is long.", "cat": "adjective"},
  {"w": "male", "ipa": "/meɪl/", "zh": "男性的", "pos": "adj.", "ex": "The baby is male.", "cat": "adjective"},
  {"w": "married", "ipa": "/ˈmærid/", "zh": "已婚的", "pos": "adj.", "ex": "They are married.", "cat": "adjective"},
  {"w": "material", "ipa": "/məˈtɪriəl/", "zh": "物质的", "pos": "adj.", "ex": "The cost is material.", "cat": "adjective"},
  {"w": "medical", "ipa": "/ˈmedɪkəl/", "zh": "医学的", "pos": "adj.", "ex": "He needs medical help.", "cat": "adjective"},
  {"w": "military", "ipa": "/ˈmɪləteri/", "zh": "军事的", "pos": "adj.", "ex": "The base is military.", "cat": "adjective"},
  {"w": "natural", "ipa": "/ˈnætʃrəl/", "zh": "自然的", "pos": "adj.", "ex": "This is a natural lake.", "cat": "adjective"},
  {"w": "necessary", "ipa": "/ˈnesəseri/", "zh": "必要的", "pos": "adj.", "ex": "Water is necessary.", "cat": "adjective"},
  {"w": "new", "ipa": "/njuː/", "zh": "新的", "pos": "adj.", "ex": "The car is new.", "cat": "adjective"},
  {"w": "normal", "ipa": "/ˈnɔːrml/", "zh": "正常的", "pos": "adj.", "ex": "The temperature is normal.", "cat": "adjective"},
  {"w": "open", "ipa": "/ˈoʊpən/", "zh": "开着的", "pos": "adj.", "ex": "The door is open.", "cat": "adjective"},
  {"w": "parallel", "ipa": "/ˈpærəlel/", "zh": "平行的", "pos": "adj.", "ex": "The lines are parallel.", "cat": "adjective"},
  {"w": "past", "ipa": "/pæst/", "zh": "过去的", "pos": "adj.", "ex": "The past week was busy.", "cat": "adjective"},
  {"w": "physical", "ipa": "/ˈfɪzɪkl/", "zh": "身体的", "pos": "adj.", "ex": "He has physical strength.", "cat": "adjective"},
  {"w": "political", "ipa": "/pəˈlɪtɪkl/", "zh": "政治的", "pos": "adj.", "ex": "The issue is political.", "cat": "adjective"},
  {"w": "poor", "ipa": "/pʊr/", "zh": "贫穷的", "pos": "adj.", "ex": "The man is poor.", "cat": "adjective"},
  {"w": "possible", "ipa": "/ˈpɒsəbl/", "zh": "可能的", "pos": "adj.", "ex": "This is possible.", "cat": "adjective"},
  {"w": "present", "ipa": "/ˈprezənt/", "zh": "现在的", "pos": "adj.", "ex": "He is in the present room.", "cat": "adjective"},
  {"w": "private", "ipa": "/ˈpraɪvət/", "zh": "私人的", "pos": "adj.", "ex": "This is a private letter.", "cat": "adjective"},
  {"w": "probable", "ipa": "/ˈprɒbəbl/", "zh": "可能的", "pos": "adj.", "ex": "The win is probable.", "cat": "adjective"},
  {"w": "quick", "ipa": "/kwɪk/", "zh": "快的", "pos": "adj.", "ex": "The dog is quick.", "cat": "adjective"},
  {"w": "quiet", "ipa": "/ˈkwaɪət/", "zh": "安静的", "pos": "adj.", "ex": "The library is quiet.", "cat": "adjective"},
  {"w": "ready", "ipa": "/ˈredi/", "zh": "准备好的", "pos": "adj.", "ex": "We are ready now.", "cat": "adjective"},
  {"w": "red", "ipa": "/red/", "zh": "红色的", "pos": "adj.", "ex": "The apple is red.", "cat": "adjective"},
  {"w": "regular", "ipa": "/ˈreɡjələr/", "zh": "规律的", "pos": "adj.", "ex": "He has regular habits.", "cat": "adjective"},
  {"w": "responsible", "ipa": "/rɪˈspɒnsəbl/", "zh": "负责的", "pos": "adj.", "ex": "She is responsible.", "cat": "adjective"},
  {"w": "right", "ipa": "/raɪt/", "zh": "正确的", "pos": "adj.", "ex": "Your answer is right.", "cat": "adjective"},
  {"w": "round", "ipa": "/raʊnd/", "zh": "圆的", "pos": "adj.", "ex": "The ball is round.", "cat": "adjective"},
  {"w": "same", "ipa": "/seɪm/", "zh": "相同的", "pos": "adj.", "ex": "We have the same book.", "cat": "adjective"},
  {"w": "second", "ipa": "/ˈsekənd/", "zh": "第二的", "pos": "adj.", "ex": "She won second place.", "cat": "adjective"},
  {"w": "separate", "ipa": "/ˈsepərət/", "zh": "分开的", "pos": "adj.", "ex": "They are in separate rooms.", "cat": "adjective"},
  {"w": "serious", "ipa": "/ˈsɪriəs/", "zh": "严肃的", "pos": "adj.", "ex": "He is a serious man.", "cat": "adjective"},
  {"w": "sharp", "ipa": "/ʃɑːrp/", "zh": "锋利的", "pos": "adj.", "ex": "The knife is sharp.", "cat": "adjective"},
  {"w": "smooth", "ipa": "/smuːð/", "zh": "光滑的", "pos": "adj.", "ex": "The skin is smooth.", "cat": "adjective"},
  {"w": "sticky", "ipa": "/ˈstɪki/", "zh": "粘的", "pos": "adj.", "ex": "The glue is sticky.", "cat": "adjective"},
  {"w": "stiff", "ipa": "/stɪf/", "zh": "僵硬的", "pos": "adj.", "ex": "The card is stiff.", "cat": "adjective"},
  {"w": "straight", "ipa": "/streɪt/", "zh": "直的", "pos": "adj.", "ex": "The line is straight.", "cat": "adjective"},
  {"w": "strong", "ipa": "/strɔːŋ/", "zh": "强壮的", "pos": "adj.", "ex": "The man is strong.", "cat": "adjective"},
  {"w": "sudden", "ipa": "/ˈsʌdn/", "zh": "突然的", "pos": "adj.", "ex": "A sudden noise came.", "cat": "adjective"},
  {"w": "sweet", "ipa": "/swiːt/", "zh": "甜的", "pos": "adj.", "ex": "The cake is sweet.", "cat": "adjective"},
  {"w": "tall", "ipa": "/tɔːl/", "zh": "高的", "pos": "adj.", "ex": "The girl is tall.", "cat": "adjective"},
  {"w": "thick", "ipa": "/θɪk/", "zh": "厚的", "pos": "adj.", "ex": "The book is thick.", "cat": "adjective"},
  {"w": "tight", "ipa": "/taɪt/", "zh": "紧的", "pos": "adj.", "ex": "The shoe is tight.", "cat": "adjective"},
  {"w": "tired", "ipa": "/ˈtaɪərd/", "zh": "疲倦的", "pos": "adj.", "ex": "The boy is tired.", "cat": "adjective"},
  {"w": "true", "ipa": "/truː/", "zh": "真实的", "pos": "adj.", "ex": "The story is true.", "cat": "adjective"},
  {"w": "violent", "ipa": "/ˈvaɪələnt/", "zh": "暴力的", "pos": "adj.", "ex": "The wind is violent.", "cat": "adjective"},
  {"w": "waiting", "ipa": "/ˈweɪtɪŋ/", "zh": "等待的", "pos": "adj.", "ex": "The man is waiting.", "cat": "adjective"},
  {"w": "warm", "ipa": "/wɔːrm/", "zh": "温暖的", "pos": "adj.", "ex": "The soup is warm.", "cat": "adjective"},
  {"w": "wet", "ipa": "/wet/", "zh": "湿的", "pos": "adj.", "ex": "The coat is wet.", "cat": "adjective"},
  {"w": "wide", "ipa": "/waɪd/", "zh": "宽的", "pos": "adj.", "ex": "The river is wide.", "cat": "adjective"},
  {"w": "wise", "ipa": "/waɪz/", "zh": "明智的", "pos": "adj.", "ex": "The old man is wise.", "cat": "adjective"},
  {"w": "yellow", "ipa": "/ˈjeləʊ/", "zh": "黄色的", "pos": "adj.", "ex": "The sun is yellow.", "cat": "adjective"},
  {"w": "young", "ipa": "/jʌŋ/", "zh": "年轻的", "pos": "adj.", "ex": "The woman is young.", "cat": "adjective"},
  {"w": "awake", "ipa": "/əˈweɪk/", "zh": "醒着的", "pos": "adj.", "ex": "The baby is awake now.", "cat": "adjective"},
  {"w": "bad", "ipa": "/bæd/", "zh": "坏的", "pos": "adj.", "ex": "This food tastes bad.", "cat": "adjective"},
  {"w": "bent", "ipa": "/bent/", "zh": "弯曲的", "pos": "adj.", "ex": "The bent stick is useless.", "cat": "adjective"},
  {"w": "bitter", "ipa": "/ˈbɪtər/", "zh": "苦的", "pos": "adj.", "ex": "The medicine is bitter.", "cat": "adjective"},
  {"w": "blue", "ipa": "/bluː/", "zh": "蓝色的", "pos": "adj.", "ex": "The sky is blue today.", "cat": "adjective"},
  {"w": "certain", "ipa": "/ˈsɜːrtən/", "zh": "确定的", "pos": "adj.", "ex": "I am certain he came.", "cat": "adjective"},
  {"w": "cold", "ipa": "/koʊld/", "zh": "冷的", "pos": "adj.", "ex": "The water is cold.", "cat": "adjective"},
  {"w": "complete", "ipa": "/kəmˈpliːt/", "zh": "完整的", "pos": "adj.", "ex": "The work is complete.", "cat": "adjective"},
  {"w": "cruel", "ipa": "/ˈkruːəl/", "zh": "残酷的", "pos": "adj.", "ex": "The cruel man laughed.", "cat": "adjective"},
  {"w": "dark", "ipa": "/dɑːrk/", "zh": "黑暗的", "pos": "adj.", "ex": "The room is dark.", "cat": "adjective"},
  {"w": "dead", "ipa": "/ded/", "zh": "死的", "pos": "adj.", "ex": "The flower is dead.", "cat": "adjective"},
  {"w": "dear", "ipa": "/dɪr/", "zh": "亲爱的", "pos": "adj.", "ex": "My dear friend left.", "cat": "adjective"},
  {"w": "delicate", "ipa": "/ˈdelɪkət/", "zh": "精致的", "pos": "adj.", "ex": "The delicate cup broke.", "cat": "adjective"},
  {"w": "different", "ipa": "/ˈdɪfrənt/", "zh": "不同的", "pos": "adj.", "ex": "We have different books.", "cat": "adjective"},
  {"w": "dirty", "ipa": "/ˈdɜːrti/", "zh": "脏的", "pos": "adj.", "ex": "His shoes are dirty.", "cat": "adjective"},
  {"w": "dry", "ipa": "/draɪ/", "zh": "干的", "pos": "adj.", "ex": "The cloth is dry.", "cat": "adjective"},
  {"w": "false", "ipa": "/fɔːls/", "zh": "假的", "pos": "adj.", "ex": "His story is false.", "cat": "adjective"},
  {"w": "feeble", "ipa": "/ˈfiːbəl/", "zh": "虚弱的", "pos": "adj.", "ex": "The feeble dog rested.", "cat": "adjective"},
  {"w": "female", "ipa": "/ˈfiːmeɪl/", "zh": "女性的", "pos": "adj.", "ex": "The female cat slept.", "cat": "adjective"},
  {"w": "foolish", "ipa": "/ˈfuːlɪʃ/", "zh": "愚蠢的", "pos": "adj.", "ex": "That was a foolish act.", "cat": "adjective"},
  {"w": "future", "ipa": "/ˈfjuːtʃər/", "zh": "未来的", "pos": "adj.", "ex": "Our future plan is set.", "cat": "adjective"},
  {"w": "green", "ipa": "/ɡriːn/", "zh": "绿色的", "pos": "adj.", "ex": "The green leaf fell.", "cat": "adjective"},
  {"w": "ill", "ipa": "/ɪl/", "zh": "生病的", "pos": "adj.", "ex": "She is ill today.", "cat": "adjective"},
  {"w": "last", "ipa": "/læst/", "zh": "最后的", "pos": "adj.", "ex": "He took the last seat.", "cat": "adjective"},
  {"w": "late", "ipa": "/leɪt/", "zh": "迟的", "pos": "adj.", "ex": "The train is late.", "cat": "adjective"},
  {"w": "left", "ipa": "/left/", "zh": "左边的", "pos": "adj.", "ex": "His left hand hurts.", "cat": "adjective"},
  {"w": "loose", "ipa": "/luːs/", "zh": "松的", "pos": "adj.", "ex": "The loose rope slipped.", "cat": "adjective"},
  {"w": "loud", "ipa": "/laʊd/", "zh": "大声的", "pos": "adj.", "ex": "The loud bell rang.", "cat": "adjective"},
  {"w": "low", "ipa": "/loʊ/", "zh": "低的", "pos": "adj.", "ex": "The low wall fell.", "cat": "adjective"},
  {"w": "mixed", "ipa": "/mɪkst/", "zh": "混合的", "pos": "adj.", "ex": "The mixed paint dried.", "cat": "adjective"},
  {"w": "narrow", "ipa": "/ˈnæroʊ/", "zh": "窄的", "pos": "adj.", "ex": "The narrow road bends.", "cat": "adjective"},
  {"w": "old", "ipa": "/oʊld/", "zh": "老的", "pos": "adj.", "ex": "My old car stopped.", "cat": "adjective"},
  {"w": "opposite", "ipa": "/ˈɒpəzɪt/", "zh": "相反的", "pos": "adj.", "ex": "They went opposite ways.", "cat": "adjective"},
  {"w": "public", "ipa": "/ˈpʌblɪk/", "zh": "公共的", "pos": "adj.", "ex": "The public park opened.", "cat": "adjective"},
  {"w": "rough", "ipa": "/rʌf/", "zh": "粗糙的", "pos": "adj.", "ex": "The rough wood scratched.", "cat": "adjective"},
  {"w": "sad", "ipa": "/sæd/", "zh": "悲伤的", "pos": "adj.", "ex": "The sad child cried.", "cat": "adjective"},
  {"w": "safe", "ipa": "/seɪf/", "zh": "安全的", "pos": "adj.", "ex": "The safe box locked.", "cat": "adjective"},
  {"w": "secret", "ipa": "/ˈsiːkrət/", "zh": "秘密的", "pos": "adj.", "ex": "They met in secret.", "cat": "adjective"},
  {"w": "short", "ipa": "/ʃɔːrt/", "zh": "短的", "pos": "adj.", "ex": "The short rope broke.", "cat": "adjective"},
  {"w": "shut", "ipa": "/ʃʌt/", "zh": "关闭的", "pos": "adj.", "ex": "The shut door locked.", "cat": "adjective"},
  {"w": "simple", "ipa": "/ˈsɪmpəl/", "zh": "简单的", "pos": "adj.", "ex": "The simple task finished.", "cat": "adjective"},
  {"w": "slow", "ipa": "/sloʊ/", "zh": "慢的", "pos": "adj.", "ex": "The slow turtle moved.", "cat": "adjective"},
  {"w": "small", "ipa": "/smɔːl/", "zh": "小的", "pos": "adj.", "ex": "A small bird sang.", "cat": "adjective"},
  {"w": "soft", "ipa": "/sɔːft/", "zh": "软的", "pos": "adj.", "ex": "The soft bed sank.", "cat": "adjective"},
  {"w": "solid", "ipa": "/ˈsɒlɪd/", "zh": "固体的", "pos": "adj.", "ex": "The solid ice melted.", "cat": "adjective"},
  {"w": "special", "ipa": "/ˈspeʃəl/", "zh": "特别的", "pos": "adj.", "ex": "This is a special day.", "cat": "adjective"},
  {"w": "strange", "ipa": "/streɪndʒ/", "zh": "奇怪的", "pos": "adj.", "ex": "A strange man came.", "cat": "adjective"},
  {"w": "thin", "ipa": "/θɪn/", "zh": "薄的", "pos": "adj.", "ex": "The thin paper tore.", "cat": "adjective"},
  {"w": "white", "ipa": "/waɪt/", "zh": "白色的", "pos": "adj.", "ex": "The white snow fell.", "cat": "adjective"},
  {"w": "wrong", "ipa": "/rɔːŋ/", "zh": "错误的", "pos": "adj.", "ex": "Your answer is wrong.", "cat": "adjective"}
];
